from twilio.base.domain import Domain as Domain
from twilio.rest.accounts.v1 import V1 as V1
from typing import Any

class Accounts(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def auth_token_promotion(self): ...
    @property
    def credentials(self): ...
    @property
    def secondary_auth_token(self): ...
