from twilio.base.domain import Domain as Domain
from twilio.rest.verify.v2 import V2 as V2

class Verify(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v2(self): ...
    @property
    def forms(self): ...
    @property
    def safelist(self): ...
    @property
    def services(self): ...
    @property
    def verification_attempts(self): ...
    @property
    def verification_attempts_summary(self): ...
    @property
    def templates(self): ...
