from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SettingList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class SettingPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SettingContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self, subaccount_sid=...): ...
    def update(self, advanced_features=..., voice_trace=..., subaccount_sid=...): ...

class SettingInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def advanced_features(self): ...
    @property
    def voice_trace(self): ...
    @property
    def url(self): ...
    def fetch(self, subaccount_sid=...): ...
    def update(self, advanced_features=..., voice_trace=..., subaccount_sid=...): ...
