from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class ParticipantList(ListResource):
    def __init__(self, version, conversation_sid) -> None: ...
    def create(self, identity=..., messaging_binding_address=..., messaging_binding_proxy_address=..., date_created=..., date_updated=..., attributes=..., messaging_binding_projected_address=..., role_sid=..., x_twilio_webhook_enabled=...): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class ParticipantPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ParticipantContext(InstanceContext):
    def __init__(self, version, conversation_sid, sid) -> None: ...
    def update(self, date_created=..., date_updated=..., attributes=..., role_sid=..., messaging_binding_proxy_address=..., messaging_binding_projected_address=..., identity=..., last_read_message_index=..., last_read_timestamp=..., x_twilio_webhook_enabled=...): ...
    def delete(self, x_twilio_webhook_enabled=...): ...
    def fetch(self): ...

class ParticipantInstance(InstanceResource):
    class WebhookEnabledType:
        TRUE: str
        FALSE: str
    def __init__(self, version, payload, conversation_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def conversation_sid(self): ...
    @property
    def sid(self): ...
    @property
    def identity(self): ...
    @property
    def attributes(self): ...
    @property
    def messaging_binding(self): ...
    @property
    def role_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def last_read_message_index(self): ...
    @property
    def last_read_timestamp(self): ...
    def update(self, date_created=..., date_updated=..., attributes=..., role_sid=..., messaging_binding_proxy_address=..., messaging_binding_projected_address=..., identity=..., last_read_message_index=..., last_read_timestamp=..., x_twilio_webhook_enabled=...): ...
    def delete(self, x_twilio_webhook_enabled=...): ...
    def fetch(self): ...
