from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class PlaybackGrantList(ListResource):
    def __init__(self, version, sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class PlaybackGrantPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class PlaybackGrantContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def create(self, ttl=..., access_control_allow_origin=...): ...
    def fetch(self): ...

class PlaybackGrantInstance(InstanceResource):
    def __init__(self, version, payload, sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def url(self): ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def grant(self): ...
    def create(self, ttl=..., access_control_allow_origin=...): ...
    def fetch(self): ...
