from twilio.base.version import Version as Version
from twilio.rest.accounts.v1.auth_token_promotion import AuthTokenPromotionList as AuthTokenPromotionList
from twilio.rest.accounts.v1.credential import CredentialList as CredentialList
from twilio.rest.accounts.v1.secondary_auth_token import SecondaryAuthTokenList as SecondaryAuthTokenList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def auth_token_promotion(self): ...
    @property
    def credentials(self): ...
    @property
    def secondary_auth_token(self): ...
