from _typeshed import Incomplete

def compare(string1, string2): ...
def remove_port(uri): ...
def add_port(uri): ...

class RequestValidator:
    token: Incomplete
    def __init__(self, token) -> None: ...
    def compute_signature(self, uri, params): ...
    def get_values(self, param_dict, param_name): ...
    def compute_hash(self, body): ...
    def validate(self, uri, params, signature): ...
