from twilio.compat import izip as izip, parse_qs as parse_qs, urlparse as urlparse
from typing import Any

def compare(string1: Any, string2: Any): ...
def remove_port(uri: Any): ...
def add_port(uri: Any): ...

class RequestValidator:
    token: Any = ...
    def __init__(self, token: Any) -> None: ...
    def compute_signature(self, uri: Any, params: Any, utf: Any = ...): ...
    def compute_hash(self, body: Any): ...
    def validate(self, uri: Any, params: Any, signature: Any): ...
