from twilio.jwt import Jwt as Jwt
from typing import Any

class ClientValidationJwt(Jwt):
    credential_sid: Any = ...
    validation_payload: Any = ...
    def __init__(self, account_sid: Any, api_key_sid: Any, credential_sid: Any, private_key: Any, validation_payload: Any) -> None: ...
