from twilio.base.version import Version as Version
from twilio.rest.studio.v2.flow import FlowList as FlowList
from twilio.rest.studio.v2.flow_validate import FlowValidateList as FlowValidateList
from typing import Any

class V2(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def flows(self): ...
    @property
    def flow_validate(self): ...
