from twilio.base import serialize as serialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class FlowValidateList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def update(self, friendly_name: Any, status: Any, definition: Any, commit_message: Any = ...): ...

class FlowValidatePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FlowValidateInstance(InstanceResource):
    class Status:
        DRAFT: str = ...
        PUBLISHED: str = ...
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def valid(self): ...
