from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class AvailableAddOnExtensionList(ListResource):
    def __init__(self, version, available_add_on_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class AvailableAddOnExtensionPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class AvailableAddOnExtensionContext(InstanceContext):
    def __init__(self, version, available_add_on_sid, sid) -> None: ...
    def fetch(self): ...

class AvailableAddOnExtensionInstance(InstanceResource):
    def __init__(self, version, payload, available_add_on_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def available_add_on_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def product_name(self): ...
    @property
    def unique_name(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
