from twilio.base.domain import Domain as Domain
from twilio.rest.supersim.v1 import V1 as V1

class Supersim(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def esim_profiles(self): ...
    @property
    def fleets(self): ...
    @property
    def ip_commands(self): ...
    @property
    def networks(self): ...
    @property
    def network_access_profiles(self): ...
    @property
    def settings_updates(self): ...
    @property
    def sims(self): ...
    @property
    def sms_commands(self): ...
    @property
    def usage_records(self): ...
