from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class SampleList(ListResource):
    def __init__(self, version: Any, assistant_sid: Any, task_sid: Any) -> None: ...
    def stream(self, language: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, language: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, language: Any = ..., page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def create(self, language: Any, tagged_text: Any, source_channel: Any = ...): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class SamplePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class SampleContext(InstanceContext):
    def __init__(self, version: Any, assistant_sid: Any, task_sid: Any, sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, language: Any = ..., tagged_text: Any = ..., source_channel: Any = ...): ...
    def delete(self): ...

class SampleInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, assistant_sid: Any, task_sid: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def task_sid(self): ...
    @property
    def language(self): ...
    @property
    def assistant_sid(self): ...
    @property
    def sid(self): ...
    @property
    def tagged_text(self): ...
    @property
    def url(self): ...
    @property
    def source_channel(self): ...
    def fetch(self): ...
    def update(self, language: Any = ..., tagged_text: Any = ..., source_channel: Any = ...): ...
    def delete(self): ...
