from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class DeliveryReceiptList(ListResource):
    def __init__(self, version, conversation_sid, message_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class DeliveryReceiptPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class DeliveryReceiptContext(InstanceContext):
    def __init__(self, version, conversation_sid, message_sid, sid) -> None: ...
    def fetch(self): ...

class DeliveryReceiptInstance(InstanceResource):
    class DeliveryStatus:
        READ: str
        FAILED: str
        DELIVERED: str
        UNDELIVERED: str
        SENT: str
    def __init__(self, version, payload, conversation_sid, message_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def conversation_sid(self): ...
    @property
    def sid(self): ...
    @property
    def message_sid(self): ...
    @property
    def channel_message_sid(self): ...
    @property
    def participant_sid(self): ...
    @property
    def status(self): ...
    @property
    def error_code(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
