from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class ByocTrunkList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, friendly_name=..., voice_url=..., voice_method=..., voice_fallback_url=..., voice_fallback_method=..., status_callback_url=..., status_callback_method=..., cnam_lookup_enabled=..., connection_policy_sid=..., from_domain_sid=...): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class ByocTrunkPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ByocTrunkContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...
    def update(self, friendly_name=..., voice_url=..., voice_method=..., voice_fallback_url=..., voice_fallback_method=..., status_callback_url=..., status_callback_method=..., cnam_lookup_enabled=..., connection_policy_sid=..., from_domain_sid=...): ...
    def delete(self): ...

class ByocTrunkInstance(InstanceResource):
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def voice_url(self): ...
    @property
    def voice_method(self): ...
    @property
    def voice_fallback_url(self): ...
    @property
    def voice_fallback_method(self): ...
    @property
    def status_callback_url(self): ...
    @property
    def status_callback_method(self): ...
    @property
    def cnam_lookup_enabled(self): ...
    @property
    def connection_policy_sid(self): ...
    @property
    def from_domain_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, friendly_name=..., voice_url=..., voice_method=..., voice_fallback_url=..., voice_fallback_method=..., status_callback_url=..., status_callback_method=..., cnam_lookup_enabled=..., connection_policy_sid=..., from_domain_sid=...): ...
    def delete(self): ...
