from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class ByocTrunkList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def create(self, friendly_name: Any = ..., voice_url: Any = ..., voice_method: Any = ..., voice_fallback_url: Any = ..., voice_fallback_method: Any = ..., status_callback_url: Any = ..., status_callback_method: Any = ..., cnam_lookup_enabled: Any = ..., connection_policy_sid: Any = ..., from_domain_sid: Any = ...): ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class ByocTrunkPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class ByocTrunkContext(InstanceContext):
    def __init__(self, version: Any, sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, friendly_name: Any = ..., voice_url: Any = ..., voice_method: Any = ..., voice_fallback_url: Any = ..., voice_fallback_method: Any = ..., status_callback_url: Any = ..., status_callback_method: Any = ..., cnam_lookup_enabled: Any = ..., connection_policy_sid: Any = ..., from_domain_sid: Any = ...): ...
    def delete(self): ...

class ByocTrunkInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def voice_url(self): ...
    @property
    def voice_method(self): ...
    @property
    def voice_fallback_url(self): ...
    @property
    def voice_fallback_method(self): ...
    @property
    def status_callback_url(self): ...
    @property
    def status_callback_method(self): ...
    @property
    def cnam_lookup_enabled(self): ...
    @property
    def connection_policy_sid(self): ...
    @property
    def from_domain_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, friendly_name: Any = ..., voice_url: Any = ..., voice_method: Any = ..., voice_fallback_url: Any = ..., voice_fallback_method: Any = ..., status_callback_url: Any = ..., status_callback_method: Any = ..., cnam_lookup_enabled: Any = ..., connection_policy_sid: Any = ..., from_domain_sid: Any = ...): ...
    def delete(self): ...
