from twilio.base.domain import Domain as Domain
from twilio.rest.chat.v1 import V1 as V1
from twilio.rest.chat.v2 import V2 as V2
from twilio.rest.chat.v3 import V3 as V3

class Chat(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def v2(self): ...
    @property
    def v3(self): ...
    @property
    def credentials(self): ...
    @property
    def services(self): ...
    @property
    def channels(self): ...
