from twilio.base.domain import Domain as Domain
from twilio.rest.chat.v1 import V1 as V1
from twilio.rest.chat.v2 import V2 as V2
from typing import Any

class Chat(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def v2(self): ...
    @property
    def credentials(self): ...
    @property
    def services(self): ...
