from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class WebChannelsList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, address_sid, chat_friendly_name=..., customer_friendly_name=..., pre_engagement_data=...): ...

class WebChannelsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class WebChannelsInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def conversation_sid(self): ...
    @property
    def identity(self): ...
