from twilio.base.version import Version as Version
from twilio.rest.lookups.v1.phone_number import PhoneNumberList as PhoneNumberList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def phone_numbers(self): ...
