from _typeshed import Incomplete
from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class PhoneNumberList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self, phone_number): ...
    def __call__(self, phone_number): ...

class PhoneNumberPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class PhoneNumberContext(InstanceContext):
    def __init__(self, version, phone_number) -> None: ...
    def fetch(self, country_code=..., type=..., add_ons=..., add_ons_data=...): ...

class PhoneNumberInstance(InstanceResource):
    class Type:
        LANDLINE: str
        MOBILE: str
        VOIP: str
    def __init__(self, version, payload, phone_number: Incomplete | None = ...) -> None: ...
    @property
    def caller_name(self): ...
    @property
    def country_code(self): ...
    @property
    def phone_number(self): ...
    @property
    def national_format(self): ...
    @property
    def carrier(self): ...
    @property
    def add_ons(self): ...
    @property
    def url(self): ...
    def fetch(self, country_code=..., type=..., add_ons=..., add_ons_data=...): ...
