from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class PhoneNumberList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def get(self, phone_number: Any): ...
    def __call__(self, phone_number: Any): ...

class PhoneNumberPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class PhoneNumberContext(InstanceContext):
    def __init__(self, version: Any, phone_number: Any) -> None: ...
    def fetch(self, country_code: Any = ..., type: Any = ..., add_ons: Any = ..., add_ons_data: Any = ...): ...

class PhoneNumberInstance(InstanceResource):
    class Type:
        LANDLINE: str = ...
        MOBILE: str = ...
        VOIP: str = ...
    def __init__(self, version: Any, payload: Any, phone_number: Optional[Any] = ...) -> None: ...
    @property
    def caller_name(self): ...
    @property
    def country_code(self): ...
    @property
    def phone_number(self): ...
    @property
    def national_format(self): ...
    @property
    def carrier(self): ...
    @property
    def add_ons(self): ...
    @property
    def url(self): ...
    def fetch(self, country_code: Any = ..., type: Any = ..., add_ons: Any = ..., add_ons_data: Any = ...): ...
