from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.preview.marketplace.installed_add_on.installed_add_on_extension import InstalledAddOnExtensionList as InstalledAddOnExtensionList
from typing import Any, Optional

class InstalledAddOnList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def create(self, available_add_on_sid: Any, accept_terms_of_service: Any, configuration: Any = ..., unique_name: Any = ...): ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class InstalledAddOnPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class InstalledAddOnContext(InstanceContext):
    def __init__(self, version: Any, sid: Any) -> None: ...
    def delete(self): ...
    def fetch(self): ...
    def update(self, configuration: Any = ..., unique_name: Any = ...): ...
    @property
    def extensions(self): ...

class InstalledAddOnInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def description(self): ...
    @property
    def configuration(self): ...
    @property
    def unique_name(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def delete(self): ...
    def fetch(self): ...
    def update(self, configuration: Any = ..., unique_name: Any = ...): ...
    @property
    def extensions(self): ...
