from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.preview.marketplace.installed_add_on.installed_add_on_extension import InstalledAddOnExtensionList as InstalledAddOnExtensionList

class InstalledAddOnList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, available_add_on_sid, accept_terms_of_service, configuration=..., unique_name=...): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class InstalledAddOnPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class InstalledAddOnContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def delete(self): ...
    def fetch(self): ...
    def update(self, configuration=..., unique_name=...): ...
    @property
    def extensions(self): ...

class InstalledAddOnInstance(InstanceResource):
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def description(self): ...
    @property
    def configuration(self): ...
    @property
    def unique_name(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def delete(self): ...
    def fetch(self): ...
    def update(self, configuration=..., unique_name=...): ...
    @property
    def extensions(self): ...
