from twilio.base.version import Version as Version
from twilio.rest.wireless.v1.command import CommandList as CommandList
from twilio.rest.wireless.v1.rate_plan import RatePlanList as RatePlanList
from twilio.rest.wireless.v1.sim import SimList as SimList
from twilio.rest.wireless.v1.usage_record import UsageRecordList as UsageRecordList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def usage_records(self): ...
    @property
    def commands(self): ...
    @property
    def rate_plans(self): ...
    @property
    def sims(self): ...
