from twilio.base.domain import Domain as Domain
from twilio.rest.media.v1 import V1 as V1

class Media(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def media_processor(self): ...
    @property
    def media_recording(self): ...
    @property
    def player_streamer(self): ...
