from twilio.base.domain import Domain as Domain
from twilio.rest.events.v1 import V1 as V1
from typing import Any

class Events(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def event_types(self): ...
    @property
    def schemas(self): ...
    @property
    def sinks(self): ...
    @property
    def subscriptions(self): ...
