from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class AssistantFallbackActionsList(ListResource):
    def __init__(self, version: Any, assistant_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class AssistantFallbackActionsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class AssistantFallbackActionsContext(InstanceContext):
    def __init__(self, version: Any, assistant_sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, fallback_actions: Any = ...): ...

class AssistantFallbackActionsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, assistant_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def assistant_sid(self): ...
    @property
    def url(self): ...
    @property
    def data(self): ...
    def fetch(self): ...
    def update(self, fallback_actions: Any = ...): ...
