from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class DialogueList(ListResource):
    def __init__(self, version: Any, assistant_sid: Any) -> None: ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class DialoguePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class DialogueContext(InstanceContext):
    def __init__(self, version: Any, assistant_sid: Any, sid: Any) -> None: ...
    def fetch(self): ...

class DialogueInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, assistant_sid: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def assistant_sid(self): ...
    @property
    def sid(self): ...
    @property
    def data(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
