from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class QueryList(ListResource):
    def __init__(self, version, assistant_sid) -> None: ...
    def stream(self, language=..., model_build=..., status=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, language=..., model_build=..., status=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, language=..., model_build=..., status=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, language, query, tasks=..., model_build=..., field=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class QueryPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class QueryContext(InstanceContext):
    def __init__(self, version, assistant_sid, sid) -> None: ...
    def fetch(self): ...
    def update(self, sample_sid=..., status=...): ...
    def delete(self): ...

class QueryInstance(InstanceResource):
    def __init__(self, version, payload, assistant_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def results(self): ...
    @property
    def language(self): ...
    @property
    def model_build_sid(self): ...
    @property
    def query(self): ...
    @property
    def sample_sid(self): ...
    @property
    def assistant_sid(self): ...
    @property
    def sid(self): ...
    @property
    def status(self): ...
    @property
    def url(self): ...
    @property
    def source_channel(self): ...
    def fetch(self): ...
    def update(self, sample_sid=..., status=...): ...
    def delete(self): ...
