from twilio.base.domain import Domain as Domain
from twilio.rest.conversations.v1 import V1 as V1

class Conversations(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def configuration(self): ...
    @property
    def address_configurations(self): ...
    @property
    def conversations(self): ...
    @property
    def credentials(self): ...
    @property
    def participant_conversations(self): ...
    @property
    def roles(self): ...
    @property
    def services(self): ...
    @property
    def users(self): ...
