from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.api.v2010.account.sip.credential_list import CredentialListList as CredentialListList
from twilio.rest.api.v2010.account.sip.domain import DomainList as DomainList
from twilio.rest.api.v2010.account.sip.ip_access_control_list import IpAccessControlListList as IpAccessControlListList

class SipList(ListResource):
    def __init__(self, version, account_sid) -> None: ...
    @property
    def domains(self): ...
    @property
    def ip_access_control_lists(self): ...
    @property
    def credential_lists(self): ...

class SipPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SipInstance(InstanceResource):
    def __init__(self, version, payload, account_sid) -> None: ...
