from twilio.jwt import Jwt as Jwt
from typing import Any, Optional

class AccessTokenGrant:
    @property
    def key(self) -> None: ...
    def to_payload(self) -> None: ...

class AccessToken(Jwt):
    account_sid: Any = ...
    signing_key_sid: Any = ...
    identity: Any = ...
    grants: Any = ...
    def __init__(self, account_sid: Any, signing_key_sid: Any, secret: Any, grants: Optional[Any] = ..., identity: Optional[Any] = ..., nbf: Any = ..., ttl: int = ..., valid_until: Optional[Any] = ...) -> None: ...
    def add_grant(self, grant: AccessTokenGrant) -> None: ...
