from _typeshed import Incomplete
from twilio.jwt.access_token import AccessTokenGrant as AccessTokenGrant

def deprecated(func): ...

class ChatGrant(AccessTokenGrant):
    service_sid: Incomplete
    endpoint_id: Incomplete
    deployment_role_sid: Incomplete
    push_credential_sid: Incomplete
    def __init__(self, service_sid: Incomplete | None = ..., endpoint_id: Incomplete | None = ..., deployment_role_sid: Incomplete | None = ..., push_credential_sid: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class IpMessagingGrant(AccessTokenGrant):
    service_sid: Incomplete
    endpoint_id: Incomplete
    deployment_role_sid: Incomplete
    push_credential_sid: Incomplete
    def __init__(self, service_sid: Incomplete | None = ..., endpoint_id: Incomplete | None = ..., deployment_role_sid: Incomplete | None = ..., push_credential_sid: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class SyncGrant(AccessTokenGrant):
    service_sid: Incomplete
    endpoint_id: Incomplete
    def __init__(self, service_sid: Incomplete | None = ..., endpoint_id: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class VoiceGrant(AccessTokenGrant):
    incoming_allow: Incomplete
    outgoing_application_sid: Incomplete
    outgoing_application_params: Incomplete
    push_credential_sid: Incomplete
    endpoint_id: Incomplete
    def __init__(self, incoming_allow: Incomplete | None = ..., outgoing_application_sid: Incomplete | None = ..., outgoing_application_params: Incomplete | None = ..., push_credential_sid: Incomplete | None = ..., endpoint_id: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class ConversationsGrant(AccessTokenGrant):
    configuration_profile_sid: Incomplete
    def __init__(self, configuration_profile_sid: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class VideoGrant(AccessTokenGrant):
    room: Incomplete
    def __init__(self, room: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class TaskRouterGrant(AccessTokenGrant):
    workspace_sid: Incomplete
    worker_sid: Incomplete
    role: Incomplete
    def __init__(self, workspace_sid: Incomplete | None = ..., worker_sid: Incomplete | None = ..., role: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...

class PlaybackGrant(AccessTokenGrant):
    grant: Incomplete
    def __init__(self, grant: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    def to_payload(self): ...
