from twilio.base.domain import Domain as Domain
from twilio.rest.messaging.v1 import V1 as V1

class Messaging(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def brand_registrations(self): ...
    @property
    def deactivations(self): ...
    @property
    def domain_certs(self): ...
    @property
    def domain_config(self): ...
    @property
    def external_campaign(self): ...
    @property
    def services(self): ...
    @property
    def tollfree_verifications(self): ...
    @property
    def usecases(self): ...
