from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class BrandedCallList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def create(self, from_: Any, to: Any, reason: Any, call_sid: Any = ...): ...

class BrandedCallPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class BrandedCallInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def bg_color(self): ...
    @property
    def brand_sid(self): ...
    @property
    def branded_channel_sid(self): ...
    @property
    def business_sid(self): ...
    @property
    def call_sid(self): ...
    @property
    def caller(self): ...
    @property
    def created_at(self): ...
    @property
    def font_color(self): ...
    @property
    def from_(self): ...
    @property
    def logo(self): ...
    @property
    def phone_number_sid(self): ...
    @property
    def reason(self): ...
    @property
    def sid(self): ...
    @property
    def status(self): ...
    @property
    def to(self): ...
    @property
    def url(self): ...
    @property
    def use_case(self): ...
