from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class BrandsInformationList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class BrandsInformationPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class BrandsInformationContext(InstanceContext):
    def __init__(self, version: Any) -> None: ...
    def fetch(self, if_none_match: Any = ...): ...

class BrandsInformationInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def update_time(self): ...
    @property
    def file_link(self): ...
    @property
    def file_link_ttl_in_seconds(self): ...
    @property
    def url(self): ...
    def fetch(self, if_none_match: Any = ...): ...
