from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class CurrentCallList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class CurrentCallPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class CurrentCallContext(InstanceContext):
    def __init__(self, version: Any) -> None: ...
    def fetch(self, x_xcnam_sensitive_phone_number_from: Any = ..., x_xcnam_sensitive_phone_number_to: Any = ...): ...

class CurrentCallInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def bg_color(self): ...
    @property
    def caller(self): ...
    @property
    def created_at(self): ...
    @property
    def font_color(self): ...
    @property
    def from_(self): ...
    @property
    def logo(self): ...
    @property
    def manager(self): ...
    @property
    def reason(self): ...
    @property
    def shield_img(self): ...
    @property
    def sid(self): ...
    @property
    def status(self): ...
    @property
    def to(self): ...
    @property
    def url(self): ...
    @property
    def use_case(self): ...
    def fetch(self, x_xcnam_sensitive_phone_number_from: Any = ..., x_xcnam_sensitive_phone_number_to: Any = ...): ...
