from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class PhoneCallList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def create(self, from_: Any, to: Any, reason: Any = ..., application_sid: Any = ..., caller_id: Any = ..., fallback_method: Any = ..., fallback_url: Any = ..., machine_detection: Any = ..., machine_detection_silence_timeout: Any = ..., machine_detection_speech_end_threshold: Any = ..., machine_detection_speech_threshold: Any = ..., machine_detection_timeout: Any = ..., method: Any = ..., record: Any = ..., recording_channels: Any = ..., recording_status_callback: Any = ..., recording_status_callback_event: Any = ..., recording_status_callback_method: Any = ..., send_digits: Any = ..., sip_auth_password: Any = ..., sip_auth_username: Any = ..., status_callback: Any = ..., status_callback_event: Any = ..., status_callback_method: Any = ..., timeout: Any = ..., trim: Any = ..., url: Any = ...): ...

class PhoneCallPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class PhoneCallInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def bg_color(self): ...
    @property
    def brand_sid(self): ...
    @property
    def branded_channel_sid(self): ...
    @property
    def business_sid(self): ...
    @property
    def call_sid(self): ...
    @property
    def caller(self): ...
    @property
    def created_at(self): ...
    @property
    def font_color(self): ...
    @property
    def from_(self): ...
    @property
    def logo(self): ...
    @property
    def phone_number_sid(self): ...
    @property
    def reason(self): ...
    @property
    def sid(self): ...
    @property
    def status(self): ...
    @property
    def to(self): ...
    @property
    def url(self): ...
    @property
    def use_case(self): ...
