from twilio.base.version import Version as Version
from twilio.rest.flex_api.v1.assessments import AssessmentsList as AssessmentsList
from twilio.rest.flex_api.v1.channel import ChannelList as ChannelList
from twilio.rest.flex_api.v1.configuration import ConfigurationList as ConfigurationList
from twilio.rest.flex_api.v1.flex_flow import FlexFlowList as FlexFlowList
from twilio.rest.flex_api.v1.insights_assessments_comment import InsightsAssessmentsCommentList as InsightsAssessmentsCommentList
from twilio.rest.flex_api.v1.insights_questionnaires import InsightsQuestionnairesList as InsightsQuestionnairesList
from twilio.rest.flex_api.v1.insights_questionnaires_category import InsightsQuestionnairesCategoryList as InsightsQuestionnairesCategoryList
from twilio.rest.flex_api.v1.insights_questionnaires_question import InsightsQuestionnairesQuestionList as InsightsQuestionnairesQuestionList
from twilio.rest.flex_api.v1.insights_segments import InsightsSegmentsList as InsightsSegmentsList
from twilio.rest.flex_api.v1.insights_session import InsightsSessionList as InsightsSessionList
from twilio.rest.flex_api.v1.insights_settings_answersets import InsightsSettingsAnswerSetsList as InsightsSettingsAnswerSetsList
from twilio.rest.flex_api.v1.insights_settings_comment import InsightsSettingsCommentList as InsightsSettingsCommentList
from twilio.rest.flex_api.v1.insights_user_roles import InsightsUserRolesList as InsightsUserRolesList
from twilio.rest.flex_api.v1.interaction import InteractionList as InteractionList
from twilio.rest.flex_api.v1.web_channel import WebChannelList as WebChannelList

class V1(Version):
    version: str
    def __init__(self, domain) -> None: ...
    @property
    def channel(self): ...
    @property
    def configuration(self): ...
    @property
    def flex_flow(self): ...
    @property
    def assessments(self): ...
    @property
    def insights_assessments_comment(self): ...
    @property
    def insights_questionnaires(self): ...
    @property
    def insights_questionnaires_category(self): ...
    @property
    def insights_questionnaires_question(self): ...
    @property
    def insights_segments(self): ...
    @property
    def insights_session(self): ...
    @property
    def insights_settings_answer_sets(self): ...
    @property
    def insights_settings_comment(self): ...
    @property
    def insights_user_roles(self): ...
    @property
    def interaction(self): ...
    @property
    def web_channel(self): ...
