from twilio.base.version import Version as Version
from twilio.rest.flex_api.v1.channel import ChannelList as ChannelList
from twilio.rest.flex_api.v1.configuration import ConfigurationList as ConfigurationList
from twilio.rest.flex_api.v1.flex_flow import FlexFlowList as FlexFlowList
from twilio.rest.flex_api.v1.web_channel import WebChannelList as WebChannelList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def channel(self): ...
    @property
    def configuration(self): ...
    @property
    def flex_flow(self): ...
    @property
    def web_channel(self): ...
