from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class AssessmentsList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class AssessmentsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class AssessmentsContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def create(self): ...

class AssessmentsInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def url(self): ...
    def create(self): ...
