from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class InsightsSettingsAnswerSetsList(ListResource):
    def __init__(self, version) -> None: ...
    def fetch(self, token=...): ...

class InsightsSettingsAnswerSetsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class InsightsSettingsAnswerSetsInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def answer_sets(self): ...
    @property
    def answer_set_categories(self): ...
    @property
    def not_applicable(self): ...
    @property
    def url(self): ...
