from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class ActivityList(ListResource):
    def __init__(self, version, workspace_sid) -> None: ...
    def stream(self, friendly_name=..., available=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, friendly_name=..., available=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, friendly_name=..., available=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, friendly_name, available=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class ActivityPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ActivityContext(InstanceContext):
    def __init__(self, version, workspace_sid, sid) -> None: ...
    def fetch(self): ...
    def update(self, friendly_name=...): ...
    def delete(self): ...

class ActivityInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def available(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def friendly_name(self): ...
    @property
    def sid(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def update(self, friendly_name=...): ...
    def delete(self): ...
