from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class EventList(ListResource):
    def __init__(self, version, workspace_sid) -> None: ...
    def stream(self, end_date=..., event_type=..., minutes=..., reservation_sid=..., start_date=..., task_queue_sid=..., task_sid=..., worker_sid=..., workflow_sid=..., task_channel=..., sid=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, end_date=..., event_type=..., minutes=..., reservation_sid=..., start_date=..., task_queue_sid=..., task_sid=..., worker_sid=..., workflow_sid=..., task_channel=..., sid=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, end_date=..., event_type=..., minutes=..., reservation_sid=..., start_date=..., task_queue_sid=..., task_sid=..., worker_sid=..., workflow_sid=..., task_channel=..., sid=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class EventPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class EventContext(InstanceContext):
    def __init__(self, version, workspace_sid, sid) -> None: ...
    def fetch(self): ...

class EventInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def actor_sid(self): ...
    @property
    def actor_type(self): ...
    @property
    def actor_url(self): ...
    @property
    def description(self): ...
    @property
    def event_data(self): ...
    @property
    def event_date(self): ...
    @property
    def event_date_ms(self): ...
    @property
    def event_type(self): ...
    @property
    def resource_sid(self): ...
    @property
    def resource_type(self): ...
    @property
    def resource_url(self): ...
    @property
    def sid(self): ...
    @property
    def source(self): ...
    @property
    def source_ip_address(self): ...
    @property
    def url(self): ...
    @property
    def workspace_sid(self): ...
    def fetch(self): ...
