from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class TaskChannelList(ListResource):
    def __init__(self, version, workspace_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, friendly_name, unique_name, channel_optimized_routing=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class TaskChannelPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class TaskChannelContext(InstanceContext):
    def __init__(self, version, workspace_sid, sid) -> None: ...
    def fetch(self): ...
    def update(self, friendly_name=..., channel_optimized_routing=...): ...
    def delete(self): ...

class TaskChannelInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def friendly_name(self): ...
    @property
    def sid(self): ...
    @property
    def unique_name(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def channel_optimized_routing(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def update(self, friendly_name=..., channel_optimized_routing=...): ...
    def delete(self): ...
