from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class WorkspaceCumulativeStatisticsList(ListResource):
    def __init__(self, version, workspace_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WorkspaceCumulativeStatisticsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class WorkspaceCumulativeStatisticsContext(InstanceContext):
    def __init__(self, version, workspace_sid) -> None: ...
    def fetch(self, end_date=..., minutes=..., start_date=..., task_channel=..., split_by_wait_time=...): ...

class WorkspaceCumulativeStatisticsInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def avg_task_acceptance_time(self): ...
    @property
    def start_time(self): ...
    @property
    def end_time(self): ...
    @property
    def reservations_created(self): ...
    @property
    def reservations_accepted(self): ...
    @property
    def reservations_rejected(self): ...
    @property
    def reservations_timed_out(self): ...
    @property
    def reservations_canceled(self): ...
    @property
    def reservations_rescinded(self): ...
    @property
    def split_by_wait_time(self): ...
    @property
    def wait_duration_until_accepted(self): ...
    @property
    def wait_duration_until_canceled(self): ...
    @property
    def tasks_canceled(self): ...
    @property
    def tasks_completed(self): ...
    @property
    def tasks_created(self): ...
    @property
    def tasks_deleted(self): ...
    @property
    def tasks_moved(self): ...
    @property
    def tasks_timed_out_in_workflow(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, end_date=..., minutes=..., start_date=..., task_channel=..., split_by_wait_time=...): ...
