from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.serverless.v1.service.environment.deployment import DeploymentList as DeploymentList
from twilio.rest.serverless.v1.service.environment.log import LogList as LogList
from twilio.rest.serverless.v1.service.environment.variable import VariableList as VariableList

class EnvironmentList(ListResource):
    def __init__(self, version, service_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, unique_name, domain_suffix=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class EnvironmentPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class EnvironmentContext(InstanceContext):
    def __init__(self, version, service_sid, sid) -> None: ...
    def fetch(self): ...
    def delete(self): ...
    @property
    def variables(self): ...
    @property
    def deployments(self): ...
    @property
    def logs(self): ...

class EnvironmentInstance(InstanceResource):
    def __init__(self, version, payload, service_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def build_sid(self): ...
    @property
    def unique_name(self): ...
    @property
    def domain_suffix(self): ...
    @property
    def domain_name(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def delete(self): ...
    @property
    def variables(self): ...
    @property
    def deployments(self): ...
    @property
    def logs(self): ...
