from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class VariableList(ListResource):
    def __init__(self, version, service_sid, environment_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, key, value): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class VariablePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class VariableContext(InstanceContext):
    def __init__(self, version, service_sid, environment_sid, sid) -> None: ...
    def fetch(self): ...
    def update(self, key=..., value=...): ...
    def delete(self): ...

class VariableInstance(InstanceResource):
    def __init__(self, version, payload, service_sid, environment_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def environment_sid(self): ...
    @property
    def key(self): ...
    @property
    def value(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, key=..., value=...): ...
    def delete(self): ...
