from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.bulkexports.v1.export.day import DayList as DayList
from twilio.rest.bulkexports.v1.export.export_custom_job import ExportCustomJobList as ExportCustomJobList
from twilio.rest.bulkexports.v1.export.job import JobList as JobList

class ExportList(ListResource):
    def __init__(self, version) -> None: ...
    @property
    def jobs(self): ...
    def get(self, resource_type): ...
    def __call__(self, resource_type): ...

class ExportPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ExportContext(InstanceContext):
    def __init__(self, version, resource_type) -> None: ...
    def fetch(self): ...
    @property
    def days(self): ...
    @property
    def export_custom_jobs(self): ...

class ExportInstance(InstanceResource):
    def __init__(self, version, payload, resource_type: Incomplete | None = ...) -> None: ...
    @property
    def resource_type(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    @property
    def days(self): ...
    @property
    def export_custom_jobs(self): ...
