from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.bulkexports.v1.export.day import DayList as DayList
from twilio.rest.bulkexports.v1.export.export_custom_job import ExportCustomJobList as ExportCustomJobList
from twilio.rest.bulkexports.v1.export.job import JobList as JobList
from typing import Any, Optional

class ExportList(ListResource):
    def __init__(self, version: Any) -> None: ...
    @property
    def jobs(self): ...
    def get(self, resource_type: Any): ...
    def __call__(self, resource_type: Any): ...

class ExportPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class ExportContext(InstanceContext):
    def __init__(self, version: Any, resource_type: Any) -> None: ...
    def fetch(self): ...
    @property
    def days(self): ...
    @property
    def export_custom_jobs(self): ...

class ExportInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, resource_type: Optional[Any] = ...) -> None: ...
    @property
    def resource_type(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    @property
    def days(self): ...
    @property
    def export_custom_jobs(self): ...
