from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class DayList(ListResource):
    def __init__(self, version, resource_type) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, day): ...
    def __call__(self, day): ...

class DayPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class DayContext(InstanceContext):
    def __init__(self, version, resource_type, day) -> None: ...
    def fetch(self): ...

class DayInstance(InstanceResource):
    def __init__(self, version, payload, resource_type, day: Incomplete | None = ...) -> None: ...
    @property
    def redirect_to(self): ...
    @property
    def day(self): ...
    @property
    def size(self): ...
    @property
    def create_date(self): ...
    @property
    def friendly_name(self): ...
    @property
    def resource_type(self): ...
    def fetch(self): ...
