from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class ExportCustomJobList(ListResource):
    def __init__(self, version, resource_type) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, start_day, end_day, friendly_name, webhook_url=..., webhook_method=..., email=...): ...

class ExportCustomJobPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ExportCustomJobInstance(InstanceResource):
    class Status:
        ERRORDURINGRUN: str
        SUBMITTED: str
        RUNNING: str
        COMPLETEDEMPTYRECORDS: str
        COMPLETED: str
        FAILED: str
        RUNNINGTOBEDELETED: str
        DELETEDBYUSERREQUEST: str
    def __init__(self, version, payload, resource_type) -> None: ...
    @property
    def friendly_name(self): ...
    @property
    def resource_type(self): ...
    @property
    def start_day(self): ...
    @property
    def end_day(self): ...
    @property
    def webhook_url(self): ...
    @property
    def webhook_method(self): ...
    @property
    def email(self): ...
    @property
    def job_sid(self): ...
    @property
    def details(self): ...
    @property
    def job_queue_position(self): ...
    @property
    def estimated_completion_time(self): ...
