from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class OriginationUrlList(ListResource):
    def __init__(self, version, trunk_sid) -> None: ...
    def create(self, weight, priority, enabled, friendly_name, sip_url): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class OriginationUrlPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class OriginationUrlContext(InstanceContext):
    def __init__(self, version, trunk_sid, sid) -> None: ...
    def fetch(self): ...
    def delete(self): ...
    def update(self, weight=..., priority=..., enabled=..., friendly_name=..., sip_url=...): ...

class OriginationUrlInstance(InstanceResource):
    def __init__(self, version, payload, trunk_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def sid(self): ...
    @property
    def trunk_sid(self): ...
    @property
    def weight(self): ...
    @property
    def enabled(self): ...
    @property
    def sip_url(self): ...
    @property
    def friendly_name(self): ...
    @property
    def priority(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def delete(self): ...
    def update(self, weight=..., priority=..., enabled=..., friendly_name=..., sip_url=...): ...
