from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class RecordingList(ListResource):
    def __init__(self, version: Any, trunk_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class RecordingPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class RecordingContext(InstanceContext):
    def __init__(self, version: Any, trunk_sid: Any) -> None: ...
    def fetch(self): ...
    def update(self): ...

class RecordingInstance(InstanceResource):
    class RecordingMode:
        DO_NOT_RECORD: str = ...
        RECORD_FROM_RINGING: str = ...
        RECORD_FROM_ANSWER: str = ...
        RECORD_FROM_RINGING_DUAL: str = ...
        RECORD_FROM_ANSWER_DUAL: str = ...
    class RecordingTrim:
        TRIM_SILENCE: str = ...
        DO_NOT_TRIM: str = ...
    def __init__(self, version: Any, payload: Any, trunk_sid: Any) -> None: ...
    @property
    def mode(self): ...
    @property
    def trim(self): ...
    @property
    def url(self): ...
    @property
    def trunk_sid(self): ...
    def fetch(self): ...
    def update(self): ...
