from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class RecordingList(ListResource):
    def __init__(self, version, trunk_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class RecordingPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class RecordingContext(InstanceContext):
    def __init__(self, version, trunk_sid) -> None: ...
    def fetch(self): ...
    def update(self, mode=..., trim=...): ...

class RecordingInstance(InstanceResource):
    class RecordingMode:
        DO_NOT_RECORD: str
        RECORD_FROM_RINGING: str
        RECORD_FROM_ANSWER: str
        RECORD_FROM_RINGING_DUAL: str
        RECORD_FROM_ANSWER_DUAL: str
    class RecordingTrim:
        TRIM_SILENCE: str
        DO_NOT_TRIM: str
    def __init__(self, version, payload, trunk_sid) -> None: ...
    @property
    def mode(self): ...
    @property
    def trim(self): ...
    def fetch(self): ...
    def update(self, mode=..., trim=...): ...
