from twilio.base.domain import Domain as Domain
from twilio.rest.video.v1 import V1 as V1
from typing import Any

class Video(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def compositions(self): ...
    @property
    def composition_hooks(self): ...
    @property
    def composition_settings(self): ...
    @property
    def recordings(self): ...
    @property
    def recording_settings(self): ...
    @property
    def rooms(self): ...
