from twilio.base.version import Version as Version
from twilio.rest.messaging.v1.deactivation import DeactivationsList as DeactivationsList
from twilio.rest.messaging.v1.service import ServiceList as ServiceList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def deactivations(self): ...
    @property
    def services(self): ...
