from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class DeactivationsList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class DeactivationsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class DeactivationsContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self, date=...): ...

class DeactivationsInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def redirect_to(self): ...
    def fetch(self, date=...): ...
