from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class DomainCertsList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self, domain_sid): ...
    def __call__(self, domain_sid): ...

class DomainCertsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class DomainCertsContext(InstanceContext):
    def __init__(self, version, domain_sid) -> None: ...
    def update(self, tls_cert): ...
    def fetch(self): ...
    def delete(self): ...

class DomainCertsInstance(InstanceResource):
    def __init__(self, version, payload, domain_sid: Incomplete | None = ...) -> None: ...
    @property
    def domain_sid(self): ...
    @property
    def date_updated(self): ...
    @property
    def date_expires(self): ...
    @property
    def date_created(self): ...
    @property
    def domain_name(self): ...
    @property
    def certificate_sid(self): ...
    @property
    def url(self): ...
    @property
    def validated(self): ...
    def update(self, tls_cert): ...
    def fetch(self): ...
    def delete(self): ...
