from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class CompositionSettingsList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class CompositionSettingsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class CompositionSettingsContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self): ...
    def create(self, friendly_name, aws_credentials_sid=..., encryption_key_sid=..., aws_s3_url=..., aws_storage_enabled=..., encryption_enabled=...): ...

class CompositionSettingsInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def aws_credentials_sid(self): ...
    @property
    def aws_s3_url(self): ...
    @property
    def aws_storage_enabled(self): ...
    @property
    def encryption_key_sid(self): ...
    @property
    def encryption_enabled(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def create(self, friendly_name, aws_credentials_sid=..., encryption_key_sid=..., aws_s3_url=..., aws_storage_enabled=..., encryption_enabled=...): ...
