from twilio.base.domain import Domain as Domain
from twilio.rest.lookups.v1 import V1 as V1
from twilio.rest.lookups.v2 import V2 as V2

class Lookups(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def v2(self): ...
    @property
    def phone_numbers(self): ...
