from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class AnonymizeList(ListResource):
    def __init__(self, version, room_sid, sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class AnonymizePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class AnonymizeContext(InstanceContext):
    def __init__(self, version, room_sid, sid) -> None: ...
    def update(self): ...

class AnonymizeInstance(InstanceResource):
    class Status:
        CONNECTED: str
        DISCONNECTED: str
    def __init__(self, version, payload, room_sid, sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def room_sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def status(self): ...
    @property
    def identity(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def start_time(self): ...
    @property
    def end_time(self): ...
    @property
    def duration(self): ...
    @property
    def url(self): ...
    def update(self): ...
