from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class PublishedTrackList(ListResource):
    def __init__(self, version, room_sid, participant_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class PublishedTrackPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class PublishedTrackContext(InstanceContext):
    def __init__(self, version, room_sid, participant_sid, sid) -> None: ...
    def fetch(self): ...

class PublishedTrackInstance(InstanceResource):
    class Kind:
        AUDIO: str
        VIDEO: str
        DATA: str
    def __init__(self, version, payload, room_sid, participant_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def participant_sid(self): ...
    @property
    def room_sid(self): ...
    @property
    def name(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def enabled(self): ...
    @property
    def kind(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
