from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class ApplicationList(ListResource):
    def __init__(self, version, account_sid) -> None: ...
    def create(self, api_version=..., voice_url=..., voice_method=..., voice_fallback_url=..., voice_fallback_method=..., status_callback=..., status_callback_method=..., voice_caller_id_lookup=..., sms_url=..., sms_method=..., sms_fallback_url=..., sms_fallback_method=..., sms_status_callback=..., message_status_callback=..., friendly_name=..., public_application_connect_enabled=...): ...
    def stream(self, friendly_name=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, friendly_name=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, friendly_name=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class ApplicationPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ApplicationContext(InstanceContext):
    def __init__(self, version, account_sid, sid) -> None: ...
    def delete(self): ...
    def fetch(self): ...
    def update(self, friendly_name=..., api_version=..., voice_url=..., voice_method=..., voice_fallback_url=..., voice_fallback_method=..., status_callback=..., status_callback_method=..., voice_caller_id_lookup=..., sms_url=..., sms_method=..., sms_fallback_url=..., sms_fallback_method=..., sms_status_callback=..., message_status_callback=..., public_application_connect_enabled=...): ...

class ApplicationInstance(InstanceResource):
    def __init__(self, version, payload, account_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def api_version(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def friendly_name(self): ...
    @property
    def message_status_callback(self): ...
    @property
    def sid(self): ...
    @property
    def sms_fallback_method(self): ...
    @property
    def sms_fallback_url(self): ...
    @property
    def sms_method(self): ...
    @property
    def sms_status_callback(self): ...
    @property
    def sms_url(self): ...
    @property
    def status_callback(self): ...
    @property
    def status_callback_method(self): ...
    @property
    def uri(self): ...
    @property
    def voice_caller_id_lookup(self): ...
    @property
    def voice_fallback_method(self): ...
    @property
    def voice_fallback_url(self): ...
    @property
    def voice_method(self): ...
    @property
    def voice_url(self): ...
    @property
    def public_application_connect_enabled(self): ...
    def delete(self): ...
    def fetch(self): ...
    def update(self, friendly_name=..., api_version=..., voice_url=..., voice_method=..., voice_fallback_url=..., voice_fallback_method=..., status_callback=..., status_callback_method=..., voice_caller_id_lookup=..., sms_url=..., sms_method=..., sms_fallback_url=..., sms_fallback_method=..., sms_status_callback=..., message_status_callback=..., public_application_connect_enabled=...): ...
