from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class BalanceList(ListResource):
    def __init__(self, version: Any, account_sid: Any) -> None: ...
    def fetch(self): ...

class BalancePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class BalanceInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, account_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def balance(self): ...
    @property
    def currency(self): ...
