from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class NewSigningKeyList(ListResource):
    def __init__(self, version: Any, account_sid: Any) -> None: ...
    def create(self, friendly_name: Any = ...): ...

class NewSigningKeyPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class NewSigningKeyInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, account_sid: Any) -> None: ...
    @property
    def sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def secret(self): ...
