from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class TokenList(ListResource):
    def __init__(self, version: Any, account_sid: Any) -> None: ...
    def create(self, ttl: Any = ...): ...

class TokenPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class TokenInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, account_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def ice_servers(self): ...
    @property
    def password(self): ...
    @property
    def ttl(self): ...
    @property
    def username(self): ...
