from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class ValidationRequestList(ListResource):
    def __init__(self, version: Any, account_sid: Any) -> None: ...
    def create(self, phone_number: Any, friendly_name: Any = ..., call_delay: Any = ..., extension: Any = ..., status_callback: Any = ..., status_callback_method: Any = ...): ...

class ValidationRequestPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class ValidationRequestInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, account_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def call_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def phone_number(self): ...
    @property
    def validation_code(self): ...
