from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.pricing.v1.phone_number.country import CountryList as CountryList
from typing import Any

class PhoneNumberList(ListResource):
    def __init__(self, version: Any) -> None: ...
    @property
    def countries(self): ...

class PhoneNumberPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class PhoneNumberInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
