from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.pricing.v1.phone_number.country import CountryList as CountryList

class PhoneNumberList(ListResource):
    def __init__(self, version) -> None: ...
    @property
    def countries(self): ...

class PhoneNumberPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class PhoneNumberInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def name(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
