from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class CountryList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def get(self, iso_country: Any): ...
    def __call__(self, iso_country: Any): ...

class CountryPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class CountryContext(InstanceContext):
    def __init__(self, version: Any, iso_country: Any) -> None: ...
    def fetch(self): ...

class CountryInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, iso_country: Optional[Any] = ...) -> None: ...
    @property
    def country(self): ...
    @property
    def iso_country(self): ...
    @property
    def phone_number_prices(self): ...
    @property
    def price_unit(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
