from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.events.v1.subscription.subscribed_event import SubscribedEventList as SubscribedEventList

class SubscriptionList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, sink_sid=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, sink_sid=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, sink_sid=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, description, sink_sid, types): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class SubscriptionPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SubscriptionContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...
    def update(self, description=..., sink_sid=...): ...
    def delete(self): ...
    @property
    def subscribed_events(self): ...

class SubscriptionInstance(InstanceResource):
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def description(self): ...
    @property
    def sink_sid(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def update(self, description=..., sink_sid=...): ...
    def delete(self): ...
    @property
    def subscribed_events(self): ...
