from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class SubscribedEventList(ListResource):
    def __init__(self, version: Any, subscription_sid: Any) -> None: ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...

class SubscribedEventPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class SubscribedEventInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, subscription_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def type(self): ...
    @property
    def version(self): ...
    @property
    def subscription_sid(self): ...
    @property
    def url(self): ...
