from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SubscribedEventList(ListResource):
    def __init__(self, version, subscription_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, type, schema_version=...): ...
    def get(self, type): ...
    def __call__(self, type): ...

class SubscribedEventPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SubscribedEventContext(InstanceContext):
    def __init__(self, version, subscription_sid, type) -> None: ...
    def fetch(self): ...
    def update(self, schema_version=...): ...
    def delete(self): ...

class SubscribedEventInstance(InstanceResource):
    def __init__(self, version, payload, subscription_sid, type: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def type(self): ...
    @property
    def schema_version(self): ...
    @property
    def subscription_sid(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, schema_version=...): ...
    def delete(self): ...
