from typing import Any, Optional

def lower_camel(string: Any): ...
def format_language(language: Any): ...

class TwiMLException(Exception): ...

class TwiML:
    MAP: Any = ...
    name: Any = ...
    value: Any = ...
    verbs: Any = ...
    attrs: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any): ...
    def to_xml(self, xml_declaration: bool = ...): ...
    def append(self, verb: Any): ...
    def nest(self, verb: Any): ...
    def xml(self): ...
    def add_child(self, name: Any, value: Optional[Any] = ..., **kwargs: Any): ...

class GenericNode(TwiML):
    name: Any = ...
    value: Any = ...
    def __init__(self, name: Any, value: Any, **kwargs: Any) -> None: ...
