from _typeshed import Incomplete

def lower_camel(string): ...
def format_language(language): ...

class TwiMLException(Exception): ...

class TwiML:
    MAP: Incomplete
    name: Incomplete
    value: Incomplete
    verbs: Incomplete
    attrs: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...
    def to_xml(self, xml_declaration: bool = ...): ...
    def append(self, verb): ...
    def nest(self, verb): ...
    def xml(self): ...
    def add_child(self, name, value: Incomplete | None = ..., **kwargs): ...

class GenericNode(TwiML):
    name: Incomplete
    value: Incomplete
    def __init__(self, name, value, **kwargs) -> None: ...
