from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class SinkValidateList(ListResource):
    def __init__(self, version: Any, sid: Any) -> None: ...
    def create(self, test_id: Any): ...

class SinkValidatePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class SinkValidateInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, sid: Any) -> None: ...
    @property
    def result(self): ...
