from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SyncMapItemList(ListResource):
    def __init__(self, version, service_sid, map_sid) -> None: ...
    def create(self, key, data): ...
    def stream(self, order=..., from_=..., bounds=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, order=..., from_=..., bounds=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, order=..., from_=..., bounds=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, key): ...
    def __call__(self, key): ...

class SyncMapItemPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SyncMapItemContext(InstanceContext):
    def __init__(self, version, service_sid, map_sid, key) -> None: ...
    def fetch(self): ...
    def delete(self, if_match=...): ...
    def update(self, data, if_match=...): ...

class SyncMapItemInstance(InstanceResource):
    class QueryResultOrder:
        ASC: str
        DESC: str
    class QueryFromBoundType:
        INCLUSIVE: str
        EXCLUSIVE: str
    def __init__(self, version, payload, service_sid, map_sid, key: Incomplete | None = ...) -> None: ...
    @property
    def key(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def map_sid(self): ...
    @property
    def url(self): ...
    @property
    def revision(self): ...
    @property
    def data(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def created_by(self): ...
    def fetch(self): ...
    def delete(self, if_match=...): ...
    def update(self, data, if_match=...): ...
