from twilio.base.version import Version as Version
from twilio.rest.conversations.v1.configuration import ConfigurationList as ConfigurationList
from twilio.rest.conversations.v1.conversation import ConversationList as ConversationList
from twilio.rest.conversations.v1.credential import CredentialList as CredentialList
from twilio.rest.conversations.v1.role import RoleList as RoleList
from twilio.rest.conversations.v1.service import ServiceList as ServiceList
from twilio.rest.conversations.v1.user import UserList as UserList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def configuration(self): ...
    @property
    def conversations(self): ...
    @property
    def credentials(self): ...
    @property
    def roles(self): ...
    @property
    def services(self): ...
    @property
    def users(self): ...
