from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class WorkersStatisticsList(ListResource):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WorkersStatisticsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class WorkersStatisticsContext(InstanceContext):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def fetch(self, minutes: Any = ..., start_date: Any = ..., end_date: Any = ..., task_queue_sid: Any = ..., task_queue_name: Any = ..., friendly_name: Any = ..., task_channel: Any = ...): ...

class WorkersStatisticsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, workspace_sid: Any) -> None: ...
    @property
    def realtime(self): ...
    @property
    def cumulative(self): ...
    @property
    def account_sid(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, minutes: Any = ..., start_date: Any = ..., end_date: Any = ..., task_queue_sid: Any = ..., task_queue_name: Any = ..., friendly_name: Any = ..., task_channel: Any = ...): ...
