from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class WorkerChannelList(ListResource):
    def __init__(self, version, workspace_sid, worker_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class WorkerChannelPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class WorkerChannelContext(InstanceContext):
    def __init__(self, version, workspace_sid, worker_sid, sid) -> None: ...
    def fetch(self): ...
    def update(self, capacity=..., available=...): ...

class WorkerChannelInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid, worker_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def assigned_tasks(self): ...
    @property
    def available(self): ...
    @property
    def available_capacity_percentage(self): ...
    @property
    def configured_capacity(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def sid(self): ...
    @property
    def task_channel_sid(self): ...
    @property
    def task_channel_unique_name(self): ...
    @property
    def worker_sid(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, capacity=..., available=...): ...
