from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class WorkersRealTimeStatisticsList(ListResource):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WorkersRealTimeStatisticsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class WorkersRealTimeStatisticsContext(InstanceContext):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def fetch(self, task_channel: Any = ...): ...

class WorkersRealTimeStatisticsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, workspace_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def activity_statistics(self): ...
    @property
    def total_workers(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, task_channel: Any = ...): ...
