from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class WorkersCumulativeStatisticsList(ListResource):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WorkersCumulativeStatisticsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class WorkersCumulativeStatisticsContext(InstanceContext):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def fetch(self, end_date: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ...): ...

class WorkersCumulativeStatisticsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, workspace_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def start_time(self): ...
    @property
    def end_time(self): ...
    @property
    def activity_durations(self): ...
    @property
    def reservations_created(self): ...
    @property
    def reservations_accepted(self): ...
    @property
    def reservations_rejected(self): ...
    @property
    def reservations_timed_out(self): ...
    @property
    def reservations_canceled(self): ...
    @property
    def reservations_rescinded(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, end_date: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ...): ...
