from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class WorkersCumulativeStatisticsList(ListResource):
    def __init__(self, version, workspace_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WorkersCumulativeStatisticsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class WorkersCumulativeStatisticsContext(InstanceContext):
    def __init__(self, version, workspace_sid) -> None: ...
    def fetch(self, end_date=..., minutes=..., start_date=..., task_channel=...): ...

class WorkersCumulativeStatisticsInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def start_time(self): ...
    @property
    def end_time(self): ...
    @property
    def activity_durations(self): ...
    @property
    def reservations_created(self): ...
    @property
    def reservations_accepted(self): ...
    @property
    def reservations_rejected(self): ...
    @property
    def reservations_timed_out(self): ...
    @property
    def reservations_canceled(self): ...
    @property
    def reservations_rescinded(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, end_date=..., minutes=..., start_date=..., task_channel=...): ...
