from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class WorkersStatisticsList(ListResource):
    def __init__(self, version, workspace_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WorkersStatisticsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class WorkersStatisticsContext(InstanceContext):
    def __init__(self, version, workspace_sid) -> None: ...
    def fetch(self, minutes=..., start_date=..., end_date=..., task_queue_sid=..., task_queue_name=..., friendly_name=..., task_channel=...): ...

class WorkersStatisticsInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid) -> None: ...
    @property
    def realtime(self): ...
    @property
    def cumulative(self): ...
    @property
    def account_sid(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, minutes=..., start_date=..., end_date=..., task_queue_sid=..., task_queue_name=..., friendly_name=..., task_channel=...): ...
