from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class BulkCountryUpdateList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, update_request): ...

class BulkCountryUpdatePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class BulkCountryUpdateInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def update_count(self): ...
    @property
    def update_request(self): ...
