from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class BulkCountryUpdateList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def create(self, update_request: Any): ...

class BulkCountryUpdatePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class BulkCountryUpdateInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def update_count(self): ...
    @property
    def update_request(self): ...
