from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SettingsList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class SettingsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SettingsContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self): ...
    def update(self, dialing_permissions_inheritance=...): ...

class SettingsInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def dialing_permissions_inheritance(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, dialing_permissions_inheritance=...): ...
