from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class RecordingRulesList(ListResource):
    def __init__(self, version: Any, room_sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, rules: Any = ...): ...

class RecordingRulesPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class RecordingRulesInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, room_sid: Any) -> None: ...
    @property
    def room_sid(self): ...
    @property
    def rules(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
