from twilio.base.version import Version as Version
from twilio.rest.supersim.v1.esim_profile import EsimProfileList as EsimProfileList
from twilio.rest.supersim.v1.fleet import FleetList as FleetList
from twilio.rest.supersim.v1.ip_command import IpCommandList as IpCommandList
from twilio.rest.supersim.v1.network import NetworkList as NetworkList
from twilio.rest.supersim.v1.network_access_profile import NetworkAccessProfileList as NetworkAccessProfileList
from twilio.rest.supersim.v1.settings_update import SettingsUpdateList as SettingsUpdateList
from twilio.rest.supersim.v1.sim import SimList as SimList
from twilio.rest.supersim.v1.sms_command import SmsCommandList as SmsCommandList
from twilio.rest.supersim.v1.usage_record import UsageRecordList as UsageRecordList

class V1(Version):
    version: str
    def __init__(self, domain) -> None: ...
    @property
    def esim_profiles(self): ...
    @property
    def fleets(self): ...
    @property
    def ip_commands(self): ...
    @property
    def networks(self): ...
    @property
    def network_access_profiles(self): ...
    @property
    def settings_updates(self): ...
    @property
    def sims(self): ...
    @property
    def sms_commands(self): ...
    @property
    def usage_records(self): ...
