from twilio.base.version import Version as Version
from twilio.rest.supersim.v1.command import CommandList as CommandList
from twilio.rest.supersim.v1.fleet import FleetList as FleetList
from twilio.rest.supersim.v1.network import NetworkList as NetworkList
from twilio.rest.supersim.v1.network_access_profile import NetworkAccessProfileList as NetworkAccessProfileList
from twilio.rest.supersim.v1.sim import SimList as SimList
from twilio.rest.supersim.v1.usage_record import UsageRecordList as UsageRecordList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def commands(self): ...
    @property
    def fleets(self): ...
    @property
    def networks(self): ...
    @property
    def network_access_profiles(self): ...
    @property
    def sims(self): ...
    @property
    def usage_records(self): ...
