from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class EsimProfileList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, callback_url=..., callback_method=..., eid=...): ...
    def stream(self, eid=..., sim_sid=..., status=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, eid=..., sim_sid=..., status=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, eid=..., sim_sid=..., status=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class EsimProfilePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class EsimProfileContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...

class EsimProfileInstance(InstanceResource):
    class Status:
        NEW: str
        RESERVING: str
        AVAILABLE: str
        DOWNLOADED: str
        INSTALLED: str
        FAILED: str
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def iccid(self): ...
    @property
    def sim_sid(self): ...
    @property
    def status(self): ...
    @property
    def eid(self): ...
    @property
    def smdp_plus_address(self): ...
    @property
    def error_code(self): ...
    @property
    def error_message(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
