from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class FleetList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def create(self, network_access_profile: Any, unique_name: Any = ..., data_enabled: Any = ..., data_limit: Any = ..., commands_enabled: Any = ..., commands_url: Any = ..., commands_method: Any = ...): ...
    def stream(self, network_access_profile: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, network_access_profile: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, network_access_profile: Any = ..., page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class FleetPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FleetContext(InstanceContext):
    def __init__(self, version: Any, sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, unique_name: Any = ..., network_access_profile: Any = ...): ...

class FleetInstance(InstanceResource):
    class DataMetering:
        PAYG: str = ...
    def __init__(self, version: Any, payload: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def sid(self): ...
    @property
    def unique_name(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def data_enabled(self): ...
    @property
    def data_limit(self): ...
    @property
    def data_metering(self): ...
    @property
    def commands_enabled(self): ...
    @property
    def commands_url(self): ...
    @property
    def commands_method(self): ...
    @property
    def network_access_profile_sid(self): ...
    def fetch(self): ...
    def update(self, unique_name: Any = ..., network_access_profile: Any = ...): ...
