from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class NetworkList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, iso_country=..., mcc=..., mnc=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, iso_country=..., mcc=..., mnc=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, iso_country=..., mcc=..., mnc=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class NetworkPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class NetworkContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...

class NetworkInstance(InstanceResource):
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def url(self): ...
    @property
    def iso_country(self): ...
    @property
    def identifiers(self): ...
    def fetch(self): ...
