from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.conversations.v1.service.configuration.notification import NotificationList as NotificationList
from twilio.rest.conversations.v1.service.configuration.webhook import WebhookList as WebhookList

class ConfigurationList(ListResource):
    def __init__(self, version, chat_service_sid) -> None: ...
    @property
    def notifications(self): ...
    @property
    def webhooks(self): ...
    def get(self): ...
    def __call__(self): ...

class ConfigurationPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ConfigurationContext(InstanceContext):
    def __init__(self, version, chat_service_sid) -> None: ...
    def fetch(self): ...
    def update(self, default_conversation_creator_role_sid=..., default_conversation_role_sid=..., default_chat_service_role_sid=..., reachability_enabled=...): ...

class ConfigurationInstance(InstanceResource):
    def __init__(self, version, payload, chat_service_sid) -> None: ...
    @property
    def chat_service_sid(self): ...
    @property
    def default_conversation_creator_role_sid(self): ...
    @property
    def default_conversation_role_sid(self): ...
    @property
    def default_chat_service_role_sid(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    @property
    def reachability_enabled(self): ...
    def fetch(self): ...
    def update(self, default_conversation_creator_role_sid=..., default_conversation_role_sid=..., default_chat_service_role_sid=..., reachability_enabled=...): ...
