from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class NotificationList(ListResource):
    def __init__(self, version, chat_service_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class NotificationPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class NotificationContext(InstanceContext):
    def __init__(self, version, chat_service_sid) -> None: ...
    def update(self, log_enabled=..., new_message_enabled=..., new_message_template=..., new_message_sound=..., new_message_badge_count_enabled=..., added_to_conversation_enabled=..., added_to_conversation_template=..., added_to_conversation_sound=..., removed_from_conversation_enabled=..., removed_from_conversation_template=..., removed_from_conversation_sound=..., new_message_with_media_enabled=..., new_message_with_media_template=...): ...
    def fetch(self): ...

class NotificationInstance(InstanceResource):
    def __init__(self, version, payload, chat_service_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def chat_service_sid(self): ...
    @property
    def new_message(self): ...
    @property
    def added_to_conversation(self): ...
    @property
    def removed_from_conversation(self): ...
    @property
    def log_enabled(self): ...
    @property
    def url(self): ...
    def update(self, log_enabled=..., new_message_enabled=..., new_message_template=..., new_message_sound=..., new_message_badge_count_enabled=..., added_to_conversation_enabled=..., added_to_conversation_template=..., added_to_conversation_sound=..., removed_from_conversation_enabled=..., removed_from_conversation_template=..., removed_from_conversation_sound=..., new_message_with_media_enabled=..., new_message_with_media_template=...): ...
    def fetch(self): ...
