from twilio.base.version import Version as Version
from twilio.rest.monitor.v1.alert import AlertList as AlertList
from twilio.rest.monitor.v1.event import EventList as EventList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def alerts(self): ...
    @property
    def events(self): ...
