from twilio.base.domain import Domain as Domain
from twilio.rest.monitor.v1 import V1 as V1
from typing import Any

class Monitor(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def alerts(self): ...
    @property
    def events(self): ...
