from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class BillingPeriodList(ListResource):
    def __init__(self, version, sim_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...

class BillingPeriodPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class BillingPeriodInstance(InstanceResource):
    class BpType:
        READY: str
        ACTIVE: str
    def __init__(self, version, payload, sim_sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def sim_sid(self): ...
    @property
    def start_time(self): ...
    @property
    def end_time(self): ...
    @property
    def period_type(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
