from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SimIpAddressList(ListResource):
    def __init__(self, version, sim_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...

class SimIpAddressPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SimIpAddressInstance(InstanceResource):
    class IpAddressVersion:
        IPV4: str
        IPV6: str
    def __init__(self, version, payload, sim_sid) -> None: ...
    @property
    def ip_address(self): ...
    @property
    def ip_address_version(self): ...
