from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class TaskQueueCumulativeStatisticsList(ListResource):
    def __init__(self, version: Any, workspace_sid: Any, task_queue_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class TaskQueueCumulativeStatisticsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class TaskQueueCumulativeStatisticsContext(InstanceContext):
    def __init__(self, version: Any, workspace_sid: Any, task_queue_sid: Any) -> None: ...
    def fetch(self, end_date: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ...): ...

class TaskQueueCumulativeStatisticsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, workspace_sid: Any, task_queue_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def avg_task_acceptance_time(self): ...
    @property
    def start_time(self): ...
    @property
    def end_time(self): ...
    @property
    def reservations_created(self): ...
    @property
    def reservations_accepted(self): ...
    @property
    def reservations_rejected(self): ...
    @property
    def reservations_timed_out(self): ...
    @property
    def reservations_canceled(self): ...
    @property
    def reservations_rescinded(self): ...
    @property
    def split_by_wait_time(self): ...
    @property
    def task_queue_sid(self): ...
    @property
    def wait_duration_until_accepted(self): ...
    @property
    def wait_duration_until_canceled(self): ...
    @property
    def wait_duration_in_queue_until_accepted(self): ...
    @property
    def tasks_canceled(self): ...
    @property
    def tasks_completed(self): ...
    @property
    def tasks_deleted(self): ...
    @property
    def tasks_entered(self): ...
    @property
    def tasks_moved(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, end_date: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ...): ...
