from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class TaskQueueStatisticsList(ListResource):
    def __init__(self, version: Any, workspace_sid: Any, task_queue_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class TaskQueueStatisticsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class TaskQueueStatisticsContext(InstanceContext):
    def __init__(self, version: Any, workspace_sid: Any, task_queue_sid: Any) -> None: ...
    def fetch(self, end_date: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ...): ...

class TaskQueueStatisticsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, workspace_sid: Any, task_queue_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def cumulative(self): ...
    @property
    def realtime(self): ...
    @property
    def task_queue_sid(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, end_date: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ...): ...
