from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class TaskQueueStatisticsList(ListResource):
    def __init__(self, version, workspace_sid, task_queue_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class TaskQueueStatisticsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class TaskQueueStatisticsContext(InstanceContext):
    def __init__(self, version, workspace_sid, task_queue_sid) -> None: ...
    def fetch(self, end_date=..., minutes=..., start_date=..., task_channel=..., split_by_wait_time=...): ...

class TaskQueueStatisticsInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid, task_queue_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def cumulative(self): ...
    @property
    def realtime(self): ...
    @property
    def task_queue_sid(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, end_date=..., minutes=..., start_date=..., task_channel=..., split_by_wait_time=...): ...
