from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class TaskQueueRealTimeStatisticsList(ListResource):
    def __init__(self, version, workspace_sid, task_queue_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class TaskQueueRealTimeStatisticsPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class TaskQueueRealTimeStatisticsContext(InstanceContext):
    def __init__(self, version, workspace_sid, task_queue_sid) -> None: ...
    def fetch(self, task_channel=...): ...

class TaskQueueRealTimeStatisticsInstance(InstanceResource):
    def __init__(self, version, payload, workspace_sid, task_queue_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def activity_statistics(self): ...
    @property
    def longest_task_waiting_age(self): ...
    @property
    def longest_task_waiting_sid(self): ...
    @property
    def longest_relative_task_age_in_queue(self): ...
    @property
    def longest_relative_task_sid_in_queue(self): ...
    @property
    def task_queue_sid(self): ...
    @property
    def tasks_by_priority(self): ...
    @property
    def tasks_by_status(self): ...
    @property
    def total_available_workers(self): ...
    @property
    def total_eligible_workers(self): ...
    @property
    def total_tasks(self): ...
    @property
    def workspace_sid(self): ...
    @property
    def url(self): ...
    def fetch(self, task_channel=...): ...
