from twilio.base import serialize as serialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class TaskQueuesStatisticsList(ListResource):
    def __init__(self, version: Any, workspace_sid: Any) -> None: ...
    def stream(self, end_date: Any = ..., friendly_name: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, end_date: Any = ..., friendly_name: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, end_date: Any = ..., friendly_name: Any = ..., minutes: Any = ..., start_date: Any = ..., task_channel: Any = ..., split_by_wait_time: Any = ..., page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...

class TaskQueuesStatisticsPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class TaskQueuesStatisticsInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, workspace_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def cumulative(self): ...
    @property
    def realtime(self): ...
    @property
    def task_queue_sid(self): ...
    @property
    def workspace_sid(self): ...
