from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.api.v2010.account.available_phone_number.local import LocalList as LocalList
from twilio.rest.api.v2010.account.available_phone_number.machine_to_machine import MachineToMachineList as MachineToMachineList
from twilio.rest.api.v2010.account.available_phone_number.mobile import MobileList as MobileList
from twilio.rest.api.v2010.account.available_phone_number.national import NationalList as NationalList
from twilio.rest.api.v2010.account.available_phone_number.shared_cost import SharedCostList as SharedCostList
from twilio.rest.api.v2010.account.available_phone_number.toll_free import TollFreeList as TollFreeList
from twilio.rest.api.v2010.account.available_phone_number.voip import VoipList as VoipList

class AvailablePhoneNumberCountryList(ListResource):
    def __init__(self, version, account_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, country_code): ...
    def __call__(self, country_code): ...

class AvailablePhoneNumberCountryPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class AvailablePhoneNumberCountryContext(InstanceContext):
    def __init__(self, version, account_sid, country_code) -> None: ...
    def fetch(self): ...
    @property
    def local(self): ...
    @property
    def toll_free(self): ...
    @property
    def mobile(self): ...
    @property
    def national(self): ...
    @property
    def voip(self): ...
    @property
    def shared_cost(self): ...
    @property
    def machine_to_machine(self): ...

class AvailablePhoneNumberCountryInstance(InstanceResource):
    def __init__(self, version, payload, account_sid, country_code: Incomplete | None = ...) -> None: ...
    @property
    def country_code(self): ...
    @property
    def country(self): ...
    @property
    def uri(self): ...
    @property
    def beta(self): ...
    @property
    def subresource_uris(self): ...
    def fetch(self): ...
    @property
    def local(self): ...
    @property
    def toll_free(self): ...
    @property
    def mobile(self): ...
    @property
    def national(self): ...
    @property
    def voip(self): ...
    @property
    def shared_cost(self): ...
    @property
    def machine_to_machine(self): ...
