from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SchemaVersionList(ListResource):
    def __init__(self, version, id) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, schema_version): ...
    def __call__(self, schema_version): ...

class SchemaVersionPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SchemaVersionContext(InstanceContext):
    def __init__(self, version, id, schema_version) -> None: ...
    def fetch(self): ...

class SchemaVersionInstance(InstanceResource):
    def __init__(self, version, payload, id, schema_version: Incomplete | None = ...) -> None: ...
    @property
    def id(self): ...
    @property
    def schema_version(self): ...
    @property
    def date_created(self): ...
    @property
    def url(self): ...
    @property
    def raw(self): ...
    def fetch(self): ...
