from twilio.base.domain import Domain as Domain
from twilio.rest.studio.v1 import V1 as V1
from twilio.rest.studio.v2 import V2 as V2
from typing import Any

class Studio(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def v2(self): ...
    @property
    def flows(self): ...
    @property
    def flow_validate(self): ...
