from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class ExportCustomJobList(ListResource):
    def __init__(self, version: Any, resource_type: Any) -> None: ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def create(self, start_day: Any, end_day: Any, friendly_name: Any, webhook_url: Any = ..., webhook_method: Any = ..., email: Any = ...): ...

class ExportCustomJobPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class ExportCustomJobInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, resource_type: Any) -> None: ...
    @property
    def friendly_name(self): ...
    @property
    def resource_type(self): ...
    @property
    def start_day(self): ...
    @property
    def end_day(self): ...
    @property
    def webhook_url(self): ...
    @property
    def webhook_method(self): ...
    @property
    def email(self): ...
    @property
    def job_sid(self): ...
    @property
    def details(self): ...
