from twilio.compat import urlencode as urlencode
from twilio.jwt import Jwt as Jwt
from typing import Any, Dict, Optional

class ClientCapabilityToken(Jwt):
    account_sid: str = ...
    auth_token: str = ...
    client_name: Optional[str] = ...
    capabilities: Dict[str, Any] = ...
    def __init__(self, account_sid: str, auth_token: str, nbf: Any = ..., ttl: int = ..., valid_until: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def allow_client_outgoing(self, application_sid: Any, **kwargs: Any) -> None: ...
    def allow_client_incoming(self, client_name: str) -> None: ...
    def allow_event_stream(self, **kwargs: Any) -> None: ...

class ScopeURI:
    service: Any = ...
    privilege: Any = ...
    params: Any = ...
    def __init__(self, service: Any, privilege: Any, params: Optional[Any] = ...) -> None: ...
    def add_param(self, key: Any, value: Any) -> None: ...
    def to_payload(self) -> str: ...
