from _typeshed import Incomplete
from twilio.jwt import Jwt as Jwt

class ClientCapabilityToken(Jwt):
    ALGORITHM: str
    account_sid: Incomplete
    auth_token: Incomplete
    client_name: Incomplete
    capabilities: Incomplete
    def __init__(self, account_sid, auth_token, nbf=..., ttl: int = ..., valid_until: Incomplete | None = ..., **kwargs) -> None: ...
    def allow_client_outgoing(self, application_sid, **kwargs) -> None: ...
    def allow_client_incoming(self, client_name) -> None: ...
    def allow_event_stream(self, **kwargs) -> None: ...

class ScopeURI:
    service: Incomplete
    privilege: Incomplete
    params: Incomplete
    def __init__(self, service, privilege, params: Incomplete | None = ...) -> None: ...
    def add_param(self, key, value) -> None: ...
    def to_payload(self): ...
