from typing import Any, Optional

class JwtDecodeError(Exception): ...

class Jwt:
    GENERATE: Any = ...
    secret_key: Any = ...
    issuer: Any = ...
    subject: Any = ...
    algorithm: Any = ...
    nbf: Any = ...
    ttl: Any = ...
    valid_until: Any = ...
    def __init__(self, secret_key: Any, issuer: Any, subject: Optional[Any] = ..., algorithm: str = ..., nbf: Any = ..., ttl: int = ..., valid_until: Optional[Any] = ...) -> None: ...
    @property
    def payload(self): ...
    @property
    def headers(self): ...
    def to_jwt(self, algorithm: Optional[Any] = ..., ttl: Optional[Any] = ...): ...
    @classmethod
    def from_jwt(cls, jwt: Any, key: str = ...): ...
