from typing import Any, Dict, Optional

class JwtDecodeError(Exception): ...

class Jwt:
    GENERATE: Any = ...
    secret_key: str = ...
    issuer: str = ...
    subject: Optional[str] = ...
    algorithm: str = ...
    nbf: int = ...
    ttl: int = ...
    valid_until: int = ...
    def __init__(self, secret_key: str, issuer: str, subject: Optional[str] = ..., algorithm: str = ..., nbf: int = ..., ttl: int = ..., valid_until: Optional[int] = ...) -> None: ...
    @property
    def payload(self) -> Dict: ...
    @property
    def headers(self) -> Dict: ...
    def to_jwt(self, algorithm: Optional[Any] = ..., ttl: Optional[Any] = ...): ...
    @classmethod
    def from_jwt(cls, jwt: Any, key: str = ...): ...
