from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class AccessTokenList(ListResource):
    def __init__(self, version: Any, service_sid: Any) -> None: ...
    def create(self, identity: Any, factor_type: Any): ...

class AccessTokenPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class AccessTokenInstance(InstanceResource):
    class FactorTypes:
        PUSH: str = ...
    def __init__(self, version: Any, payload: Any, service_sid: Any) -> None: ...
    @property
    def token(self): ...
