from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class VerificationCheckList(ListResource):
    def __init__(self, version: Any, service_sid: Any) -> None: ...
    def create(self, code: Any, to: Any = ..., verification_sid: Any = ..., amount: Any = ..., payee: Any = ...): ...

class VerificationCheckPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class VerificationCheckInstance(InstanceResource):
    class Channel:
        SMS: str = ...
        CALL: str = ...
        EMAIL: str = ...
    def __init__(self, version: Any, payload: Any, service_sid: Any) -> None: ...
    @property
    def sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def to(self): ...
    @property
    def channel(self): ...
    @property
    def status(self): ...
    @property
    def valid(self): ...
    @property
    def amount(self): ...
    @property
    def payee(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
