from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class VerificationCheckList(ListResource):
    def __init__(self, version, service_sid) -> None: ...
    def create(self, code=..., to=..., verification_sid=..., amount=..., payee=...): ...

class VerificationCheckPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class VerificationCheckInstance(InstanceResource):
    class Channel:
        SMS: str
        CALL: str
        EMAIL: str
        WHATSAPP: str
        SNA: str
    def __init__(self, version, payload, service_sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def to(self): ...
    @property
    def channel(self): ...
    @property
    def status(self): ...
    @property
    def valid(self): ...
    @property
    def amount(self): ...
    @property
    def payee(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def sna_attempts_error_codes(self): ...
