from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class NumberList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self, number): ...
    def __call__(self, number): ...

class NumberPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class NumberContext(InstanceContext):
    def __init__(self, version, number) -> None: ...
    def fetch(self): ...

class NumberInstance(InstanceResource):
    def __init__(self, version, payload, number: Incomplete | None = ...) -> None: ...
    @property
    def number(self): ...
    @property
    def country(self): ...
    @property
    def iso_country(self): ...
    @property
    def outbound_call_price(self): ...
    @property
    def inbound_call_price(self): ...
    @property
    def price_unit(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
