from twilio.base.domain import Domain as Domain
from twilio.rest.insights.v1 import V1 as V1

class Insights(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def settings(self): ...
    @property
    def calls(self): ...
    @property
    def call_summaries(self): ...
    @property
    def conferences(self): ...
    @property
    def rooms(self): ...
