from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class FeedbackList(ListResource):
    def __init__(self, version: Any, account_sid: Any, message_sid: Any) -> None: ...
    def create(self, outcome: Any = ...): ...

class FeedbackPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FeedbackInstance(InstanceResource):
    class Outcome:
        CONFIRMED: str = ...
        UNCONFIRMED: str = ...
    def __init__(self, version: Any, payload: Any, account_sid: Any, message_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def message_sid(self): ...
    @property
    def outcome(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def uri(self): ...
