from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class FeedbackList(ListResource):
    def __init__(self, version, account_sid, message_sid) -> None: ...
    def create(self, outcome=...): ...

class FeedbackPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class FeedbackInstance(InstanceResource):
    class Outcome:
        CONFIRMED: str
        UNCONFIRMED: str
    def __init__(self, version, payload, account_sid, message_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def message_sid(self): ...
    @property
    def outcome(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def uri(self): ...
