from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class MediaList(ListResource):
    def __init__(self, version: Any, account_sid: Any, message_sid: Any) -> None: ...
    def stream(self, date_created_before: Any = ..., date_created: Any = ..., date_created_after: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, date_created_before: Any = ..., date_created: Any = ..., date_created_after: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, date_created_before: Any = ..., date_created: Any = ..., date_created_after: Any = ..., page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class MediaPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class MediaContext(InstanceContext):
    def __init__(self, version: Any, account_sid: Any, message_sid: Any, sid: Any) -> None: ...
    def delete(self): ...
    def fetch(self): ...

class MediaInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, account_sid: Any, message_sid: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def content_type(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def parent_sid(self): ...
    @property
    def sid(self): ...
    @property
    def uri(self): ...
    def delete(self): ...
    def fetch(self): ...
