from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class MediaList(ListResource):
    def __init__(self, version, account_sid, message_sid) -> None: ...
    def stream(self, date_created_before=..., date_created=..., date_created_after=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, date_created_before=..., date_created=..., date_created_after=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, date_created_before=..., date_created=..., date_created_after=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class MediaPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class MediaContext(InstanceContext):
    def __init__(self, version, account_sid, message_sid, sid) -> None: ...
    def delete(self): ...
    def fetch(self): ...

class MediaInstance(InstanceResource):
    def __init__(self, version, payload, account_sid, message_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def content_type(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def parent_sid(self): ...
    @property
    def sid(self): ...
    @property
    def uri(self): ...
    def delete(self): ...
    def fetch(self): ...
