from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.proxy.v1.service.session.participant.message_interaction import MessageInteractionList as MessageInteractionList

class ParticipantList(ListResource):
    def __init__(self, version, service_sid, session_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, identifier, friendly_name=..., proxy_identifier=..., proxy_identifier_sid=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class ParticipantPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ParticipantContext(InstanceContext):
    def __init__(self, version, service_sid, session_sid, sid) -> None: ...
    def fetch(self): ...
    def delete(self): ...
    @property
    def message_interactions(self): ...

class ParticipantInstance(InstanceResource):
    def __init__(self, version, payload, service_sid, session_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def session_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def identifier(self): ...
    @property
    def proxy_identifier(self): ...
    @property
    def proxy_identifier_sid(self): ...
    @property
    def date_deleted(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def delete(self): ...
    @property
    def message_interactions(self): ...
