from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class MetricList(ListResource):
    def __init__(self, version, call_sid) -> None: ...
    def stream(self, edge=..., direction=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, edge=..., direction=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, edge=..., direction=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...

class MetricPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class MetricInstance(InstanceResource):
    class TwilioEdge:
        UNKNOWN_EDGE: str
        CARRIER_EDGE: str
        SIP_EDGE: str
        SDK_EDGE: str
        CLIENT_EDGE: str
    class StreamDirection:
        UNKNOWN: str
        INBOUND: str
        OUTBOUND: str
        BOTH: str
    def __init__(self, version, payload, call_sid) -> None: ...
    @property
    def timestamp(self): ...
    @property
    def call_sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def edge(self): ...
    @property
    def direction(self): ...
    @property
    def carrier_edge(self): ...
    @property
    def sip_edge(self): ...
    @property
    def sdk_edge(self): ...
    @property
    def client_edge(self): ...
