from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.api.v2010.account.queue.member import MemberList as MemberList
from typing import Any, Optional

class QueueList(ListResource):
    def __init__(self, version: Any, account_sid: Any) -> None: ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def create(self, friendly_name: Any, max_size: Any = ...): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class QueuePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class QueueContext(InstanceContext):
    def __init__(self, version: Any, account_sid: Any, sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, friendly_name: Any = ..., max_size: Any = ...): ...
    def delete(self): ...
    @property
    def members(self): ...

class QueueInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, account_sid: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def date_updated(self): ...
    @property
    def current_size(self): ...
    @property
    def friendly_name(self): ...
    @property
    def uri(self): ...
    @property
    def account_sid(self): ...
    @property
    def average_wait_time(self): ...
    @property
    def sid(self): ...
    @property
    def date_created(self): ...
    @property
    def max_size(self): ...
    def fetch(self): ...
    def update(self, friendly_name: Any = ..., max_size: Any = ...): ...
    def delete(self): ...
    @property
    def members(self): ...
