from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class FunctionVersionContentList(ListResource):
    def __init__(self, version: Any, service_sid: Any, function_sid: Any, sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class FunctionVersionContentPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FunctionVersionContentContext(InstanceContext):
    def __init__(self, version: Any, service_sid: Any, function_sid: Any, sid: Any) -> None: ...
    def fetch(self): ...

class FunctionVersionContentInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, service_sid: Any, function_sid: Any, sid: Any) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def function_sid(self): ...
    @property
    def content(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
