from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class FunctionVersionContentList(ListResource):
    def __init__(self, version, service_sid, function_sid, sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class FunctionVersionContentPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class FunctionVersionContentContext(InstanceContext):
    def __init__(self, version, service_sid, function_sid, sid) -> None: ...
    def fetch(self): ...

class FunctionVersionContentInstance(InstanceResource):
    def __init__(self, version, payload, service_sid, function_sid, sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def function_sid(self): ...
    @property
    def content(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
