from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.conversations.v1.configuration.webhook import WebhookList as WebhookList

class ConfigurationList(ListResource):
    def __init__(self, version) -> None: ...
    @property
    def webhooks(self): ...
    def get(self): ...
    def __call__(self): ...

class ConfigurationPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class ConfigurationContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self): ...
    def update(self, default_chat_service_sid=..., default_messaging_service_sid=..., default_inactive_timer=..., default_closed_timer=...): ...

class ConfigurationInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def default_chat_service_sid(self): ...
    @property
    def default_messaging_service_sid(self): ...
    @property
    def default_inactive_timer(self): ...
    @property
    def default_closed_timer(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def update(self, default_chat_service_sid=..., default_messaging_service_sid=..., default_inactive_timer=..., default_closed_timer=...): ...
