from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class WebhookList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class WebhookPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class WebhookContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self): ...
    def update(self, method=..., filters=..., pre_webhook_url=..., post_webhook_url=..., target=...): ...

class WebhookInstance(InstanceResource):
    class Target:
        WEBHOOK: str
        FLEX: str
    class Method:
        GET: str
        POST: str
    def __init__(self, version, payload) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def method(self): ...
    @property
    def filters(self): ...
    @property
    def pre_webhook_url(self): ...
    @property
    def post_webhook_url(self): ...
    @property
    def target(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, method=..., filters=..., pre_webhook_url=..., post_webhook_url=..., target=...): ...
