from twilio.base.domain import Domain as Domain
from twilio.rest.trusthub.v1 import V1 as V1

class Trusthub(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def customer_profiles(self): ...
    @property
    def end_users(self): ...
    @property
    def end_user_types(self): ...
    @property
    def policies(self): ...
    @property
    def supporting_documents(self): ...
    @property
    def supporting_document_types(self): ...
    @property
    def trust_products(self): ...
