from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class NotificationList(ListResource):
    def __init__(self, version, service_sid, identity, challenge_sid) -> None: ...
    def create(self, ttl=...): ...

class NotificationPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class NotificationInstance(InstanceResource):
    def __init__(self, version, payload, service_sid, identity, challenge_sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def entity_sid(self): ...
    @property
    def identity(self): ...
    @property
    def challenge_sid(self): ...
    @property
    def priority(self): ...
    @property
    def ttl(self): ...
    @property
    def date_created(self): ...
