from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.sync.v1.service.document.document_permission import DocumentPermissionList as DocumentPermissionList

class DocumentList(ListResource):
    def __init__(self, version, service_sid) -> None: ...
    def create(self, unique_name=..., data=..., ttl=...): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class DocumentPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class DocumentContext(InstanceContext):
    def __init__(self, version, service_sid, sid) -> None: ...
    def fetch(self): ...
    def delete(self): ...
    def update(self, data=..., ttl=..., if_match=...): ...
    @property
    def document_permissions(self): ...

class DocumentInstance(InstanceResource):
    def __init__(self, version, payload, service_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def unique_name(self): ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    @property
    def revision(self): ...
    @property
    def data(self): ...
    @property
    def date_expires(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def created_by(self): ...
    def fetch(self): ...
    def delete(self): ...
    def update(self, data=..., ttl=..., if_match=...): ...
    @property
    def document_permissions(self): ...
