from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class BundleCopyList(ListResource):
    def __init__(self, version, bundle_sid) -> None: ...
    def create(self, friendly_name=...): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...

class BundleCopyPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class BundleCopyInstance(InstanceResource):
    class Status:
        DRAFT: str
        PENDING_REVIEW: str
        IN_REVIEW: str
        TWILIO_REJECTED: str
        TWILIO_APPROVED: str
        PROVISIONALLY_APPROVED: str
    class EndUserType:
        INDIVIDUAL: str
        BUSINESS: str
    def __init__(self, version, payload, bundle_sid) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def regulation_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def status(self): ...
    @property
    def valid_until(self): ...
    @property
    def email(self): ...
    @property
    def status_callback(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
