from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.pricing.v1.messaging.country import CountryList as CountryList
from typing import Any

class MessagingList(ListResource):
    def __init__(self, version: Any) -> None: ...
    @property
    def countries(self): ...

class MessagingPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class MessagingInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
