from twilio.jwt.taskrouter import TaskRouterCapabilityToken as TaskRouterCapabilityToken
from typing import Any

class WorkerCapabilityToken(TaskRouterCapabilityToken):
    def __init__(self, account_sid: Any, auth_token: Any, workspace_sid: Any, worker_sid: Any, ttl: int = ..., **kwargs: Any) -> None: ...
    @property
    def resource_url(self): ...
    @property
    def channel_prefix(self): ...
    def allow_fetch_activities(self) -> None: ...
    def allow_fetch_reservations(self) -> None: ...
    def allow_fetch_worker_reservations(self) -> None: ...
    def allow_update_activities(self) -> None: ...
    def allow_update_reservations(self) -> None: ...

class TaskQueueCapabilityToken(TaskRouterCapabilityToken):
    def __init__(self, account_sid: Any, auth_token: Any, workspace_sid: Any, task_queue_sid: Any, ttl: int = ..., **kwargs: Any) -> None: ...
    @property
    def resource_url(self): ...
    @property
    def channel_prefix(self): ...

class WorkspaceCapabilityToken(TaskRouterCapabilityToken):
    def __init__(self, account_sid: Any, auth_token: Any, workspace_sid: Any, ttl: int = ..., **kwargs: Any) -> None: ...
    @property
    def resource_url(self): ...
    @property
    def channel_prefix(self): ...
