from twilio.base.domain import Domain as Domain
from twilio.rest.flex_api.v1 import V1 as V1
from typing import Any

class FlexApi(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def channel(self): ...
    @property
    def configuration(self): ...
    @property
    def flex_flow(self): ...
    @property
    def web_channel(self): ...
