from twilio.base.domain import Domain as Domain
from twilio.rest.voice.v1 import V1 as V1
from typing import Any

class Voice(Domain):
    base_url: str = ...
    def __init__(self, twilio: Any) -> None: ...
    @property
    def v1(self): ...
    @property
    def byoc_trunks(self): ...
    @property
    def connection_policies(self): ...
    @property
    def dialing_permissions(self): ...
    @property
    def ip_records(self): ...
    @property
    def source_ip_mappings(self): ...
