from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class UsAppToPersonList(ListResource):
    def __init__(self, version, messaging_service_sid) -> None: ...
    def create(self, brand_registration_sid, description, message_flow, message_samples, us_app_to_person_usecase, has_embedded_links, has_embedded_phone, opt_in_message=..., opt_out_message=..., help_message=..., opt_in_keywords=..., opt_out_keywords=..., help_keywords=...): ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class UsAppToPersonPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class UsAppToPersonContext(InstanceContext):
    def __init__(self, version, messaging_service_sid, sid) -> None: ...
    def delete(self): ...
    def fetch(self): ...

class UsAppToPersonInstance(InstanceResource):
    def __init__(self, version, payload, messaging_service_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def brand_registration_sid(self): ...
    @property
    def messaging_service_sid(self): ...
    @property
    def description(self): ...
    @property
    def message_samples(self): ...
    @property
    def us_app_to_person_usecase(self): ...
    @property
    def has_embedded_links(self): ...
    @property
    def has_embedded_phone(self): ...
    @property
    def campaign_status(self): ...
    @property
    def campaign_id(self): ...
    @property
    def is_externally_registered(self): ...
    @property
    def rate_limits(self): ...
    @property
    def message_flow(self): ...
    @property
    def opt_in_message(self): ...
    @property
    def opt_out_message(self): ...
    @property
    def help_message(self): ...
    @property
    def opt_in_keywords(self): ...
    @property
    def opt_out_keywords(self): ...
    @property
    def help_keywords(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def mock(self): ...
    def delete(self): ...
    def fetch(self): ...
