from twilio.base import values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class UsAppToPersonUsecaseList(ListResource):
    def __init__(self, version, messaging_service_sid) -> None: ...
    def fetch(self, brand_registration_sid=...): ...

class UsAppToPersonUsecasePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class UsAppToPersonUsecaseInstance(InstanceResource):
    def __init__(self, version, payload, messaging_service_sid) -> None: ...
    @property
    def us_app_to_person_usecases(self): ...
