from twilio.base.version import Version as Version
from twilio.rest.api.v2010.account import AccountContext as AccountContext, AccountList as AccountList
from typing import Any

class V2010(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def accounts(self): ...
    @property
    def account(self): ...
    @account.setter
    def account(self, value: Any) -> None: ...
    @property
    def addresses(self): ...
    @property
    def applications(self): ...
    @property
    def authorized_connect_apps(self): ...
    @property
    def available_phone_numbers(self): ...
    @property
    def balance(self): ...
    @property
    def calls(self): ...
    @property
    def conferences(self): ...
    @property
    def connect_apps(self): ...
    @property
    def incoming_phone_numbers(self): ...
    @property
    def keys(self): ...
    @property
    def messages(self): ...
    @property
    def new_keys(self): ...
    @property
    def new_signing_keys(self): ...
    @property
    def notifications(self): ...
    @property
    def outgoing_caller_ids(self): ...
    @property
    def queues(self): ...
    @property
    def recordings(self): ...
    @property
    def signing_keys(self): ...
    @property
    def sip(self): ...
    @property
    def short_codes(self): ...
    @property
    def tokens(self): ...
    @property
    def transcriptions(self): ...
    @property
    def usage(self): ...
    @property
    def validation_requests(self): ...
