from twilio.base import serialize as serialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class UsageRecordList(ListResource):
    def __init__(self, version: Any, sim_sid: Any) -> None: ...
    def stream(self, end: Any = ..., start: Any = ..., granularity: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, end: Any = ..., start: Any = ..., granularity: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, end: Any = ..., start: Any = ..., granularity: Any = ..., page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...

class UsageRecordPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class UsageRecordInstance(InstanceResource):
    class Granularity:
        HOURLY: str = ...
        DAILY: str = ...
        ALL: str = ...
    def __init__(self, version: Any, payload: Any, sim_sid: Any) -> None: ...
    @property
    def sim_sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def period(self): ...
    @property
    def commands(self): ...
    @property
    def data(self): ...
