from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class FeedbackList(ListResource):
    def __init__(self, version, account_sid, call_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class FeedbackPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class FeedbackContext(InstanceContext):
    def __init__(self, version, account_sid, call_sid) -> None: ...
    def fetch(self): ...
    def create(self, quality_score, issue=...): ...
    def update(self, quality_score=..., issue=...): ...

class FeedbackInstance(InstanceResource):
    class Issues:
        AUDIO_LATENCY: str
        DIGITS_NOT_CAPTURED: str
        DROPPED_CALL: str
        IMPERFECT_AUDIO: str
        INCORRECT_CALLER_ID: str
        ONE_WAY_AUDIO: str
        POST_DIAL_DELAY: str
        UNSOLICITED_CALL: str
    def __init__(self, version, payload, account_sid, call_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def issues(self): ...
    @property
    def quality_score(self): ...
    @property
    def sid(self): ...
    def fetch(self): ...
    def create(self, quality_score, issue=...): ...
    def update(self, quality_score=..., issue=...): ...
