from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class FeedbackSummaryList(ListResource):
    def __init__(self, version, account_sid) -> None: ...
    def create(self, start_date, end_date, include_subaccounts=..., status_callback=..., status_callback_method=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class FeedbackSummaryPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class FeedbackSummaryContext(InstanceContext):
    def __init__(self, version, account_sid, sid) -> None: ...
    def fetch(self): ...
    def delete(self): ...

class FeedbackSummaryInstance(InstanceResource):
    class Status:
        QUEUED: str
        IN_PROGRESS: str
        COMPLETED: str
        FAILED: str
    def __init__(self, version, payload, account_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def call_count(self): ...
    @property
    def call_feedback_count(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def end_date(self): ...
    @property
    def include_subaccounts(self): ...
    @property
    def issues(self): ...
    @property
    def quality_score_average(self): ...
    @property
    def quality_score_median(self): ...
    @property
    def quality_score_standard_deviation(self): ...
    @property
    def sid(self): ...
    @property
    def start_date(self): ...
    @property
    def status(self): ...
    def fetch(self): ...
    def delete(self): ...
