from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class FeedbackList(ListResource):
    def __init__(self, version: Any, account_sid: Any, call_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class FeedbackPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FeedbackContext(InstanceContext):
    def __init__(self, version: Any, account_sid: Any, call_sid: Any) -> None: ...
    def create(self, quality_score: Any, issue: Any = ...): ...
    def fetch(self): ...
    def update(self, quality_score: Any, issue: Any = ...): ...

class FeedbackInstance(InstanceResource):
    class Issues:
        AUDIO_LATENCY: str = ...
        DIGITS_NOT_CAPTURED: str = ...
        DROPPED_CALL: str = ...
        IMPERFECT_AUDIO: str = ...
        INCORRECT_CALLER_ID: str = ...
        ONE_WAY_AUDIO: str = ...
        POST_DIAL_DELAY: str = ...
        UNSOLICITED_CALL: str = ...
    def __init__(self, version: Any, payload: Any, account_sid: Any, call_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def issues(self): ...
    @property
    def quality_score(self): ...
    @property
    def sid(self): ...
    def create(self, quality_score: Any, issue: Any = ...): ...
    def fetch(self): ...
    def update(self, quality_score: Any, issue: Any = ...): ...
