from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class StreamList(ListResource):
    def __init__(self, version, account_sid, call_sid) -> None: ...
    def create(self, url, name=..., track=..., status_callback=..., status_callback_method=..., parameter1_name=..., parameter1_value=..., parameter2_name=..., parameter2_value=..., parameter3_name=..., parameter3_value=..., parameter4_name=..., parameter4_value=..., parameter5_name=..., parameter5_value=..., parameter6_name=..., parameter6_value=..., parameter7_name=..., parameter7_value=..., parameter8_name=..., parameter8_value=..., parameter9_name=..., parameter9_value=..., parameter10_name=..., parameter10_value=..., parameter11_name=..., parameter11_value=..., parameter12_name=..., parameter12_value=..., parameter13_name=..., parameter13_value=..., parameter14_name=..., parameter14_value=..., parameter15_name=..., parameter15_value=..., parameter16_name=..., parameter16_value=..., parameter17_name=..., parameter17_value=..., parameter18_name=..., parameter18_value=..., parameter19_name=..., parameter19_value=..., parameter20_name=..., parameter20_value=..., parameter21_name=..., parameter21_value=..., parameter22_name=..., parameter22_value=..., parameter23_name=..., parameter23_value=..., parameter24_name=..., parameter24_value=..., parameter25_name=..., parameter25_value=..., parameter26_name=..., parameter26_value=..., parameter27_name=..., parameter27_value=..., parameter28_name=..., parameter28_value=..., parameter29_name=..., parameter29_value=..., parameter30_name=..., parameter30_value=..., parameter31_name=..., parameter31_value=..., parameter32_name=..., parameter32_value=..., parameter33_name=..., parameter33_value=..., parameter34_name=..., parameter34_value=..., parameter35_name=..., parameter35_value=..., parameter36_name=..., parameter36_value=..., parameter37_name=..., parameter37_value=..., parameter38_name=..., parameter38_value=..., parameter39_name=..., parameter39_value=..., parameter40_name=..., parameter40_value=..., parameter41_name=..., parameter41_value=..., parameter42_name=..., parameter42_value=..., parameter43_name=..., parameter43_value=..., parameter44_name=..., parameter44_value=..., parameter45_name=..., parameter45_value=..., parameter46_name=..., parameter46_value=..., parameter47_name=..., parameter47_value=..., parameter48_name=..., parameter48_value=..., parameter49_name=..., parameter49_value=..., parameter50_name=..., parameter50_value=..., parameter51_name=..., parameter51_value=..., parameter52_name=..., parameter52_value=..., parameter53_name=..., parameter53_value=..., parameter54_name=..., parameter54_value=..., parameter55_name=..., parameter55_value=..., parameter56_name=..., parameter56_value=..., parameter57_name=..., parameter57_value=..., parameter58_name=..., parameter58_value=..., parameter59_name=..., parameter59_value=..., parameter60_name=..., parameter60_value=..., parameter61_name=..., parameter61_value=..., parameter62_name=..., parameter62_value=..., parameter63_name=..., parameter63_value=..., parameter64_name=..., parameter64_value=..., parameter65_name=..., parameter65_value=..., parameter66_name=..., parameter66_value=..., parameter67_name=..., parameter67_value=..., parameter68_name=..., parameter68_value=..., parameter69_name=..., parameter69_value=..., parameter70_name=..., parameter70_value=..., parameter71_name=..., parameter71_value=..., parameter72_name=..., parameter72_value=..., parameter73_name=..., parameter73_value=..., parameter74_name=..., parameter74_value=..., parameter75_name=..., parameter75_value=..., parameter76_name=..., parameter76_value=..., parameter77_name=..., parameter77_value=..., parameter78_name=..., parameter78_value=..., parameter79_name=..., parameter79_value=..., parameter80_name=..., parameter80_value=..., parameter81_name=..., parameter81_value=..., parameter82_name=..., parameter82_value=..., parameter83_name=..., parameter83_value=..., parameter84_name=..., parameter84_value=..., parameter85_name=..., parameter85_value=..., parameter86_name=..., parameter86_value=..., parameter87_name=..., parameter87_value=..., parameter88_name=..., parameter88_value=..., parameter89_name=..., parameter89_value=..., parameter90_name=..., parameter90_value=..., parameter91_name=..., parameter91_value=..., parameter92_name=..., parameter92_value=..., parameter93_name=..., parameter93_value=..., parameter94_name=..., parameter94_value=..., parameter95_name=..., parameter95_value=..., parameter96_name=..., parameter96_value=..., parameter97_name=..., parameter97_value=..., parameter98_name=..., parameter98_value=..., parameter99_name=..., parameter99_value=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class StreamPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class StreamContext(InstanceContext):
    def __init__(self, version, account_sid, call_sid, sid) -> None: ...
    def update(self, status): ...

class StreamInstance(InstanceResource):
    class Track:
        INBOUND_TRACK: str
        OUTBOUND_TRACK: str
        BOTH_TRACKS: str
    class Status:
        IN_PROGRESS: str
        STOPPED: str
    class UpdateStatus:
        STOPPED: str
    def __init__(self, version, payload, account_sid, call_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def call_sid(self): ...
    @property
    def name(self): ...
    @property
    def status(self): ...
    @property
    def date_updated(self): ...
    @property
    def uri(self): ...
    def update(self, status): ...
