from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class UserChannelList(ListResource):
    def __init__(self, version, service_sid, user_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...

class UserChannelPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class UserChannelInstance(InstanceResource):
    class ChannelStatus:
        JOINED: str
        INVITED: str
        NOT_PARTICIPATING: str
    def __init__(self, version, payload, service_sid, user_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def service_sid(self): ...
    @property
    def channel_sid(self): ...
    @property
    def member_sid(self): ...
    @property
    def status(self): ...
    @property
    def last_consumed_message_index(self): ...
    @property
    def unread_messages_count(self): ...
    @property
    def links(self): ...
