from twilio.base.version import Version as Version
from twilio.rest.verify.v2.form import FormList as FormList
from twilio.rest.verify.v2.service import ServiceList as ServiceList
from typing import Any

class V2(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def forms(self): ...
    @property
    def services(self): ...
