from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class FormList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def get(self, form_type: Any): ...
    def __call__(self, form_type: Any): ...

class FormPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FormContext(InstanceContext):
    def __init__(self, version: Any, form_type: Any) -> None: ...
    def fetch(self): ...

class FormInstance(InstanceResource):
    class FormTypes:
        FORM_PUSH: str = ...
    def __init__(self, version: Any, payload: Any, form_type: Optional[Any] = ...) -> None: ...
    @property
    def form_type(self): ...
    @property
    def forms(self): ...
    @property
    def form_meta(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
