from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class FormList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self, form_type): ...
    def __call__(self, form_type): ...

class FormPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class FormContext(InstanceContext):
    def __init__(self, version, form_type) -> None: ...
    def fetch(self): ...

class FormInstance(InstanceResource):
    class FormTypes:
        FORM_PUSH: str
    def __init__(self, version, payload, form_type: Incomplete | None = ...) -> None: ...
    @property
    def form_type(self): ...
    @property
    def forms(self): ...
    @property
    def form_meta(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
