from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class SafelistList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, phone_number): ...
    def get(self, phone_number): ...
    def __call__(self, phone_number): ...

class SafelistPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SafelistContext(InstanceContext):
    def __init__(self, version, phone_number) -> None: ...
    def fetch(self): ...
    def delete(self): ...

class SafelistInstance(InstanceResource):
    def __init__(self, version, payload, phone_number: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def phone_number(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def delete(self): ...
