from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class VerificationAttemptsSummaryList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class VerificationAttemptsSummaryPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class VerificationAttemptsSummaryContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self, verify_service_sid=..., date_created_after=..., date_created_before=..., country=..., channel=..., destination_prefix=...): ...

class VerificationAttemptsSummaryInstance(InstanceResource):
    class Channels:
        SMS: str
        CALL: str
        EMAIL: str
        WHATSAPP: str
    def __init__(self, version, payload) -> None: ...
    @property
    def total_attempts(self): ...
    @property
    def total_converted(self): ...
    @property
    def total_unconverted(self): ...
    @property
    def conversion_rate_percentage(self): ...
    @property
    def url(self): ...
    def fetch(self, verify_service_sid=..., date_created_after=..., date_created_before=..., country=..., channel=..., destination_prefix=...): ...
