from twilio.base.domain import Domain as Domain
from twilio.rest.oauth.v1 import V1 as V1

class Oauth(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v1(self): ...
    @property
    def oauth(self): ...
    @property
    def device_code(self): ...
    @property
    def openid_discovery(self): ...
    @property
    def token(self): ...
    @property
    def user_info(self): ...
