from twilio.base.domain import Domain as Domain
from twilio.rest.routes.v2 import V2 as V2

class Routes(Domain):
    base_url: str
    def __init__(self, twilio) -> None: ...
    @property
    def v2(self): ...
    @property
    def phone_numbers(self): ...
    @property
    def sip_domains(self): ...
    @property
    def trunks(self): ...
