from twilio.base.version import Version as Version
from twilio.rest.autopilot.v1.assistant import AssistantList as AssistantList
from twilio.rest.autopilot.v1.restore_assistant import RestoreAssistantList as RestoreAssistantList
from typing import Any

class V1(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def assistants(self): ...
    @property
    def restore_assistant(self): ...
