from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class RestoreAssistantList(ListResource):
    def __init__(self, version: Any) -> None: ...
    def update(self, assistant: Any): ...

class RestoreAssistantPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class RestoreAssistantInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def unique_name(self): ...
    @property
    def friendly_name(self): ...
    @property
    def needs_model_build(self): ...
    @property
    def latest_model_build_sid(self): ...
    @property
    def log_queries(self): ...
    @property
    def development_stage(self): ...
    @property
    def callback_url(self): ...
    @property
    def callback_events(self): ...
