from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class FieldValueList(ListResource):
    def __init__(self, version: Any, assistant_sid: Any, field_type_sid: Any) -> None: ...
    def stream(self, language: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, language: Any = ..., limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, language: Any = ..., page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...
    def create(self, language: Any, value: Any, synonym_of: Any = ...): ...
    def get(self, sid: Any): ...
    def __call__(self, sid: Any): ...

class FieldValuePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FieldValueContext(InstanceContext):
    def __init__(self, version: Any, assistant_sid: Any, field_type_sid: Any, sid: Any) -> None: ...
    def fetch(self): ...
    def delete(self): ...

class FieldValueInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, assistant_sid: Any, field_type_sid: Any, sid: Optional[Any] = ...) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def field_type_sid(self): ...
    @property
    def language(self): ...
    @property
    def assistant_sid(self): ...
    @property
    def sid(self): ...
    @property
    def value(self): ...
    @property
    def url(self): ...
    @property
    def synonym_of(self): ...
    def fetch(self): ...
    def delete(self): ...
