from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any, Optional

class DependentPhoneNumberList(ListResource):
    def __init__(self, version: Any, account_sid: Any, address_sid: Any) -> None: ...
    def stream(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def list(self, limit: Optional[Any] = ..., page_size: Optional[Any] = ...): ...
    def page(self, page_token: Any = ..., page_number: Any = ..., page_size: Any = ...): ...
    def get_page(self, target_url: Any): ...

class DependentPhoneNumberPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class DependentPhoneNumberInstance(InstanceResource):
    class AddressRequirement:
        NONE: str = ...
        ANY: str = ...
        LOCAL: str = ...
        FOREIGN: str = ...
    class EmergencyStatus:
        ACTIVE: str = ...
        INACTIVE: str = ...
    def __init__(self, version: Any, payload: Any, account_sid: Any, address_sid: Any) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def phone_number(self): ...
    @property
    def voice_url(self): ...
    @property
    def voice_method(self): ...
    @property
    def voice_fallback_method(self): ...
    @property
    def voice_fallback_url(self): ...
    @property
    def voice_caller_id_lookup(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def sms_fallback_method(self): ...
    @property
    def sms_fallback_url(self): ...
    @property
    def sms_method(self): ...
    @property
    def sms_url(self): ...
    @property
    def address_requirements(self): ...
    @property
    def capabilities(self): ...
    @property
    def status_callback(self): ...
    @property
    def status_callback_method(self): ...
    @property
    def api_version(self): ...
    @property
    def sms_application_sid(self): ...
    @property
    def voice_application_sid(self): ...
    @property
    def trunk_sid(self): ...
    @property
    def emergency_status(self): ...
    @property
    def emergency_address_sid(self): ...
    @property
    def uri(self): ...
