from twilio.compat import urlencode as urlencode
from twilio.http import HttpClient as HttpClient
from twilio.http.response import Response as Response
from typing import Any, Optional

class TwilioHttpClient(HttpClient):
    session: Any = ...
    last_request: Any = ...
    last_response: Any = ...
    logger: Any = ...
    request_hooks: Any = ...
    timeout: Any = ...
    proxy: Any = ...
    def __init__(self, pool_connections: bool = ..., request_hooks: Optional[Any] = ..., timeout: Optional[Any] = ..., logger: Any = ..., proxy: Optional[Any] = ..., max_retries: Optional[Any] = ...) -> None: ...
    def request(self, method: Any, url: Any, params: Optional[Any] = ..., data: Optional[Any] = ..., headers: Optional[Any] = ..., auth: Optional[Any] = ..., timeout: Optional[Any] = ..., allow_redirects: bool = ...): ...
