import logging

import requests
from twilio.compat import urlencode as urlencode
from twilio.http import HttpClient as HttpClient
from twilio.http.request import Request
from twilio.http.response import Response
from typing import Any, Dict, Optional, Tuple

class TwilioHttpClient(HttpClient):
    session: requests.Session = ...
    last_request: Optional[Request] = ...
    last_response: Optional[Response] = ...
    logger: logging.Logger = ...
    request_hooks: Any = ...
    timeout: Optional[int] = ...
    proxy: Any = ...

    def __init__(self, pool_connections: bool = ..., request_hooks: Optional[Any] = ..., timeout: Optional[int] = ..., logger: logging.Logger = ..., proxy: Optional[Any] = ..., max_retries: Optional[int] = ...) -> None: ...

    def request(self, method: str, url: str, params: Optional[Dict] = ..., data: Optional[Dict] = ..., headers: Optional[Dict] = ..., auth: Optional[Tuple] = ..., timeout: Optional[float] = ..., allow_redirects: bool = ...) -> Response: ...
