from twilio.compat import urlencode as urlencode
from typing import Any, Optional

class Request:
    ANY: str = ...
    method: str = ...
    url: str = ...
    auth: Optional[tuple] = ...
    params: Optional[dict] = ...
    data: Optional[dict] = ...
    headers: Optional[dict] = ...

    def __init__(self, method: str = ..., url: str = ..., auth: Optional[tuple] = ..., params: Optional[dict] = ..., data: Optional[dict] = ..., headers: Optional[dict] = ..., **kwargs: Any) -> None: ...

    @classmethod
    def attribute_equal(cls, lhs: Any, rhs: Any) -> bool: ...

    def __eq__(self, other: Any) -> bool: ...
