from twilio.compat import urlencode as urlencode
from typing import Any

class Request:
    ANY: str = ...
    method: Any = ...
    url: Any = ...
    auth: Any = ...
    params: Any = ...
    data: Any = ...
    headers: Any = ...
    def __init__(self, method: Any = ..., url: Any = ..., auth: Any = ..., params: Any = ..., data: Any = ..., headers: Any = ..., **kwargs: Any) -> None: ...
    @classmethod
    def attribute_equal(cls, lhs: Any, rhs: Any): ...
    def __eq__(self, other: Any) -> Any: ...
