from typing import Dict, Literal, Tuple, Union

class Request:
    ANY: str
    method: str = ...
    url: str = ...
    auth: Tuple = ...
    params: Dict = ...
    data: Dict = ...
    headers: Dict = ...
    def __init__(self, method=..., url=..., auth: Union[Tuple, Literal['*']]=..., params=..., data=..., headers=..., **kwargs) -> None: ...
    @classmethod
    def attribute_equal(cls, lhs, rhs): ...
    def __eq__(self, other): ...
