from typing import Any, Optional

class Response:
    content: Any = ...
    headers: Any = ...
    cached: bool = ...
    status_code: int = ...
    ok: bool = ...

    def __init__(self, status_code: Any, text: Any, headers: Optional[Any] = ...) -> None: ...

    @property
    def text(self): ...
