from typing import Any, Optional

class Response:
    content: Any = ...
    headers: Any = ...
    cached: bool = ...
    status_code: Any = ...
    ok: Any = ...
    def __init__(self, status_code: Any, text: Any, headers: Optional[Any] = ...) -> None: ...
    @property
    def text(self): ...
