from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class LocalList(ListResource):
    def __init__(self, version, account_sid) -> None: ...
    def stream(self, beta=..., friendly_name=..., phone_number=..., origin=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, beta=..., friendly_name=..., phone_number=..., origin=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, beta=..., friendly_name=..., phone_number=..., origin=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, phone_number, api_version=..., friendly_name=..., sms_application_sid=..., sms_fallback_method=..., sms_fallback_url=..., sms_method=..., sms_url=..., status_callback=..., status_callback_method=..., voice_application_sid=..., voice_caller_id_lookup=..., voice_fallback_method=..., voice_fallback_url=..., voice_method=..., voice_url=..., identity_sid=..., address_sid=..., emergency_status=..., emergency_address_sid=..., trunk_sid=..., voice_receive_mode=..., bundle_sid=...): ...

class LocalPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class LocalInstance(InstanceResource):
    class AddressRequirement:
        NONE: str
        ANY: str
        LOCAL: str
        FOREIGN: str
    class EmergencyStatus:
        ACTIVE: str
        INACTIVE: str
    class EmergencyAddressStatus:
        REGISTERED: str
        UNREGISTERED: str
        PENDING_REGISTRATION: str
        REGISTRATION_FAILURE: str
        PENDING_UNREGISTRATION: str
        UNREGISTRATION_FAILURE: str
    class VoiceReceiveMode:
        VOICE: str
        FAX: str
    def __init__(self, version, payload, account_sid) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def address_sid(self): ...
    @property
    def address_requirements(self): ...
    @property
    def api_version(self): ...
    @property
    def beta(self): ...
    @property
    def capabilities(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def friendly_name(self): ...
    @property
    def identity_sid(self): ...
    @property
    def phone_number(self): ...
    @property
    def origin(self): ...
    @property
    def sid(self): ...
    @property
    def sms_application_sid(self): ...
    @property
    def sms_fallback_method(self): ...
    @property
    def sms_fallback_url(self): ...
    @property
    def sms_method(self): ...
    @property
    def sms_url(self): ...
    @property
    def status_callback(self): ...
    @property
    def status_callback_method(self): ...
    @property
    def trunk_sid(self): ...
    @property
    def uri(self): ...
    @property
    def voice_receive_mode(self): ...
    @property
    def voice_application_sid(self): ...
    @property
    def voice_caller_id_lookup(self): ...
    @property
    def voice_fallback_method(self): ...
    @property
    def voice_fallback_url(self): ...
    @property
    def voice_method(self): ...
    @property
    def voice_url(self): ...
    @property
    def emergency_status(self): ...
    @property
    def emergency_address_sid(self): ...
    @property
    def emergency_address_status(self): ...
    @property
    def bundle_sid(self): ...
    @property
    def status(self): ...
