from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class CommandList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, device=..., sim=..., status=..., direction=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, device=..., sim=..., status=..., direction=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, device=..., sim=..., status=..., direction=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, command, device=..., sim=..., callback_method=..., callback_url=..., command_mode=..., include_sid=...): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class CommandPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class CommandContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...

class CommandInstance(InstanceResource):
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def account_sid(self): ...
    @property
    def device_sid(self): ...
    @property
    def sim_sid(self): ...
    @property
    def command(self): ...
    @property
    def command_mode(self): ...
    @property
    def status(self): ...
    @property
    def direction(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
