from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class StepContextList(ListResource):
    def __init__(self, version: Any, flow_sid: Any, engagement_sid: Any, step_sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class StepContextPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class StepContextContext(InstanceContext):
    def __init__(self, version: Any, flow_sid: Any, engagement_sid: Any, step_sid: Any) -> None: ...
    def fetch(self): ...

class StepContextInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, flow_sid: Any, engagement_sid: Any, step_sid: Any) -> None: ...
    @property
    def account_sid(self): ...
    @property
    def context(self): ...
    @property
    def engagement_sid(self): ...
    @property
    def flow_sid(self): ...
    @property
    def step_sid(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
