import datetime
from typing import Any

ISO8601_DATE_FORMAT: str
ISO8601_DATETIME_FORMAT: str

def iso8601_date(s: str) -> datetime.date: ...

def iso8601_datetime(s: str) -> datetime.datetime: ...

def rfc2822_datetime(s: str): ...

def decimal(d: Any): ...

def integer(i: str) -> int: ...
