from typing import Any, Optional

from twilio.rest import Client

class Domain:
    twilio: Client = ...

    base_url: Optional[str] = ...

    def __init__(self, twilio: Client) -> None: ...

    def absolute_url(self, uri: Any) -> str: ...

    def request(self, method: str, uri: str, params: Optional[dict] = ..., data: Optional[Any] = ..., headers: Optional[dict] = ..., auth: Optional[tuple] = ..., timeout: Optional[int] = ..., allow_redirects: bool = ...): ...
