from typing import Any, Optional

class Domain:
    twilio: Any = ...

    base_url: Any = ...

    def __init__(self, twilio: Any) -> None: ...

    def absolute_url(self, uri: Any) -> str: ...

    def request(self, method: Any, uri: Any, params: Optional[Any] = ..., data: Optional[Any] = ..., headers: Optional[Any] = ..., auth: Optional[Any] = ..., timeout: Optional[Any] = ..., allow_redirects: bool = ...): ...
