from typing import Any, Optional

class Domain:
    twilio: Any = ...

    base_url: Any = ...

    def __init__(self, twilio: Any) -> None: ...

    def absolute_url(self, uri: Any) -> str: ...

    def request(self, method: str, uri: str, params: Optional[dict] = ..., data: Optional[Any] = ..., headers: Optional[dict] = ..., auth: Optional[tuple] = ..., timeout: Optional[int] = ..., allow_redirects: bool = ...): ...
