from typing import Any, Optional

class TwilioException(Exception): ...

class TwilioRestException(TwilioException):
    uri: str = ...
    status: int = ...
    msg: str = ...
    code: Optional[int] = ...
    method: str = ...
    details: Optional[dict] = ...

    def __init__(self, status: int, uri: str, msg: str = ..., code: Optional[Any] = ..., method: str = ..., details: Optional[Any] = ...) -> None: ...
