from typing import Any, Optional

class TwilioException(Exception): ...

class TwilioRestException(TwilioException):
    uri: Any = ...
    status: Any = ...
    msg: Any = ...
    code: Any = ...
    method: Any = ...
    details: Any = ...
    def __init__(self, status: Any, uri: Any, msg: str = ..., code: Optional[Any] = ..., method: str = ..., details: Optional[Any] = ...) -> None: ...
