from twilio.base.exceptions import TwilioException as TwilioException
from typing import Any

class Page:
    META_KEYS: Any = ...
    def __init__(self, version: Any, response: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self): ...
    def next(self): ...
    @classmethod
    def process_response(cls, response: Any): ...
    def load_page(self, payload: Any): ...
    @property
    def previous_page_url(self): ...
    @property
    def next_page_url(self): ...
    def get_instance(self, payload: Any) -> None: ...
    def next_page(self): ...
    def previous_page(self): ...
