from twilio.base import values as values
from typing import Any

def iso8601_date(d: Any): ...
def iso8601_datetime(d: Any): ...
def prefixed_collapsible_map(m: Any, prefix: Any): ...
def object(obj: Any): ...
def map(lst: Any, serialize_func: Any): ...
