from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class NetworkAccessProfileNetworkList(ListResource):
    def __init__(self, version, network_access_profile_sid) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def create(self, network): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class NetworkAccessProfileNetworkPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class NetworkAccessProfileNetworkContext(InstanceContext):
    def __init__(self, version, network_access_profile_sid, sid) -> None: ...
    def delete(self): ...
    def fetch(self): ...

class NetworkAccessProfileNetworkInstance(InstanceResource):
    def __init__(self, version, payload, network_access_profile_sid, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def network_access_profile_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def iso_country(self): ...
    @property
    def identifiers(self): ...
    @property
    def url(self): ...
    def delete(self): ...
    def fetch(self): ...
