from twilio.base import deserialize as deserialize, serialize as serialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class DeviceCodeList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, client_sid, scopes, audiences=...): ...

class DeviceCodePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class DeviceCodeInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def device_code(self): ...
    @property
    def user_code(self): ...
    @property
    def verification_uri(self): ...
    @property
    def verification_uri_complete(self): ...
    @property
    def expires_in(self): ...
    @property
    def interval(self): ...
