from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class OauthList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class OauthPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class OauthContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self): ...

class OauthInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def keys(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
