from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class OpenidDiscoveryList(ListResource):
    def __init__(self, version) -> None: ...
    def get(self): ...
    def __call__(self): ...

class OpenidDiscoveryPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class OpenidDiscoveryContext(InstanceContext):
    def __init__(self, version) -> None: ...
    def fetch(self): ...

class OpenidDiscoveryInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def issuer(self): ...
    @property
    def authorization_endpoint(self): ...
    @property
    def device_authorization_endpoint(self): ...
    @property
    def token_endpoint(self): ...
    @property
    def userinfo_endpoint(self): ...
    @property
    def revocation_endpoint(self): ...
    @property
    def jwk_uri(self): ...
    @property
    def response_type_supported(self): ...
    @property
    def subject_type_supported(self): ...
    @property
    def id_token_signing_alg_values_supported(self): ...
    @property
    def scopes_supported(self): ...
    @property
    def claims_supported(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
