from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class TokenList(ListResource):
    def __init__(self, version) -> None: ...
    def create(self, grant_type, client_sid, client_secret=..., code=..., code_verifier=..., device_code=..., refresh_token=..., device_id=...): ...

class TokenPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class TokenInstance(InstanceResource):
    def __init__(self, version, payload) -> None: ...
    @property
    def access_token(self): ...
    @property
    def refresh_token(self): ...
    @property
    def id_token(self): ...
    @property
    def refresh_token_expires_at(self): ...
    @property
    def access_token_expires_at(self): ...
