from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.numbers.v2.regulatory_compliance.bundle import BundleList as BundleList
from twilio.rest.numbers.v2.regulatory_compliance.end_user import EndUserList as EndUserList
from twilio.rest.numbers.v2.regulatory_compliance.end_user_type import EndUserTypeList as EndUserTypeList
from twilio.rest.numbers.v2.regulatory_compliance.regulation import RegulationList as RegulationList
from twilio.rest.numbers.v2.regulatory_compliance.supporting_document import SupportingDocumentList as SupportingDocumentList
from twilio.rest.numbers.v2.regulatory_compliance.supporting_document_type import SupportingDocumentTypeList as SupportingDocumentTypeList
from typing import Any

class RegulatoryComplianceList(ListResource):
    def __init__(self, version: Any) -> None: ...
    @property
    def bundles(self): ...
    @property
    def end_users(self): ...
    @property
    def end_user_types(self): ...
    @property
    def regulations(self): ...
    @property
    def supporting_documents(self): ...
    @property
    def supporting_document_types(self): ...

class RegulatoryCompliancePage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class RegulatoryComplianceInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any) -> None: ...
