from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class RegulationList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, end_user_type=..., iso_country=..., number_type=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, end_user_type=..., iso_country=..., number_type=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, end_user_type=..., iso_country=..., number_type=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class RegulationPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class RegulationContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...

class RegulationInstance(InstanceResource):
    class EndUserType:
        INDIVIDUAL: str
        BUSINESS: str
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def iso_country(self): ...
    @property
    def number_type(self): ...
    @property
    def end_user_type(self): ...
    @property
    def requirements(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
