from _typeshed import Incomplete
from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class CountryList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, iso_country): ...
    def __call__(self, iso_country): ...

class CountryPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class CountryContext(InstanceContext):
    def __init__(self, version, iso_country) -> None: ...
    def fetch(self): ...

class CountryInstance(InstanceResource):
    def __init__(self, version, payload, iso_country: Incomplete | None = ...) -> None: ...
    @property
    def country(self): ...
    @property
    def iso_country(self): ...
    @property
    def terminating_prefix_prices(self): ...
    @property
    def originating_call_prices(self): ...
    @property
    def price_unit(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
