from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from twilio.rest.preview.wireless.sim.usage import UsageList as UsageList

class SimList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, status=..., iccid=..., rate_plan=..., e_id=..., sim_registration_code=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, status=..., iccid=..., rate_plan=..., e_id=..., sim_registration_code=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, status=..., iccid=..., rate_plan=..., e_id=..., sim_registration_code=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, sid): ...
    def __call__(self, sid): ...

class SimPage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class SimContext(InstanceContext):
    def __init__(self, version, sid) -> None: ...
    def fetch(self): ...
    def update(self, unique_name=..., callback_method=..., callback_url=..., friendly_name=..., rate_plan=..., status=..., commands_callback_method=..., commands_callback_url=..., sms_fallback_method=..., sms_fallback_url=..., sms_method=..., sms_url=..., voice_fallback_method=..., voice_fallback_url=..., voice_method=..., voice_url=...): ...
    @property
    def usage(self): ...

class SimInstance(InstanceResource):
    def __init__(self, version, payload, sid: Incomplete | None = ...) -> None: ...
    @property
    def sid(self): ...
    @property
    def unique_name(self): ...
    @property
    def account_sid(self): ...
    @property
    def rate_plan_sid(self): ...
    @property
    def friendly_name(self): ...
    @property
    def iccid(self): ...
    @property
    def e_id(self): ...
    @property
    def status(self): ...
    @property
    def commands_callback_url(self): ...
    @property
    def commands_callback_method(self): ...
    @property
    def sms_fallback_method(self): ...
    @property
    def sms_fallback_url(self): ...
    @property
    def sms_method(self): ...
    @property
    def sms_url(self): ...
    @property
    def voice_fallback_method(self): ...
    @property
    def voice_fallback_url(self): ...
    @property
    def voice_method(self): ...
    @property
    def voice_url(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
    def update(self, unique_name=..., callback_method=..., callback_url=..., friendly_name=..., rate_plan=..., status=..., commands_callback_method=..., commands_callback_url=..., sms_fallback_method=..., sms_fallback_url=..., sms_method=..., sms_url=..., voice_fallback_method=..., voice_fallback_url=..., voice_method=..., voice_url=...): ...
    @property
    def usage(self): ...
