from twilio.base import values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class UsageList(ListResource):
    def __init__(self, version, sim_sid) -> None: ...
    def get(self): ...
    def __call__(self): ...

class UsagePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class UsageContext(InstanceContext):
    def __init__(self, version, sim_sid) -> None: ...
    def fetch(self, end=..., start=...): ...

class UsageInstance(InstanceResource):
    def __init__(self, version, payload, sim_sid) -> None: ...
    @property
    def sim_sid(self): ...
    @property
    def sim_unique_name(self): ...
    @property
    def account_sid(self): ...
    @property
    def period(self): ...
    @property
    def commands_usage(self): ...
    @property
    def commands_costs(self): ...
    @property
    def data_usage(self): ...
    @property
    def data_costs(self): ...
    @property
    def url(self): ...
    def fetch(self, end=..., start=...): ...
