from twilio.base import serialize as serialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page
from typing import Any

class FlowTestUserList(ListResource):
    def __init__(self, version: Any, sid: Any) -> None: ...
    def get(self): ...
    def __call__(self): ...

class FlowTestUserPage(Page):
    def __init__(self, version: Any, response: Any, solution: Any) -> None: ...
    def get_instance(self, payload: Any): ...

class FlowTestUserContext(InstanceContext):
    def __init__(self, version: Any, sid: Any) -> None: ...
    def fetch(self): ...
    def update(self, test_users: Any): ...

class FlowTestUserInstance(InstanceResource):
    def __init__(self, version: Any, payload: Any, sid: Any) -> None: ...
    @property
    def sid(self): ...
    @property
    def test_users(self): ...
    @property
    def url(self): ...
    def fetch(self): ...
    def update(self, test_users: Any): ...
