from _typeshed import Incomplete
from twilio.base import deserialize as deserialize, values as values
from twilio.base.instance_context import InstanceContext as InstanceContext
from twilio.base.instance_resource import InstanceResource as InstanceResource
from twilio.base.list_resource import ListResource as ListResource
from twilio.base.page import Page as Page

class EventTypeList(ListResource):
    def __init__(self, version) -> None: ...
    def stream(self, schema_id=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def list(self, schema_id=..., limit: Incomplete | None = ..., page_size: Incomplete | None = ...): ...
    def page(self, schema_id=..., page_token=..., page_number=..., page_size=...): ...
    def get_page(self, target_url): ...
    def get(self, type): ...
    def __call__(self, type): ...

class EventTypePage(Page):
    def __init__(self, version, response, solution) -> None: ...
    def get_instance(self, payload): ...

class EventTypeContext(InstanceContext):
    def __init__(self, version, type) -> None: ...
    def fetch(self): ...

class EventTypeInstance(InstanceResource):
    def __init__(self, version, payload, type: Incomplete | None = ...) -> None: ...
    @property
    def type(self): ...
    @property
    def schema_id(self): ...
    @property
    def date_created(self): ...
    @property
    def date_updated(self): ...
    @property
    def description(self): ...
    @property
    def url(self): ...
    @property
    def links(self): ...
    def fetch(self): ...
