from twilio.base.version import Version as Version
from twilio.rest.ip_messaging.v2.credential import CredentialList as CredentialList
from twilio.rest.ip_messaging.v2.service import ServiceList as ServiceList
from typing import Any

class V2(Version):
    version: str = ...
    def __init__(self, domain: Any) -> None: ...
    @property
    def credentials(self): ...
    @property
    def services(self): ...
